import type { KanbanCustomTask, KanbanCard, TaskPriority } from "@/types";
import {
  parseDateBR,
  isValidDate,
  sameDateBR,
  addDays,
  parseDateRangeList,
  parseDiasParadosList,
  normalizeDateList,
  getTimelineColor,
  getTimelineLabel,
  isEsteiraPreProdDay,
  isHoliday,
  isPostRelease,
  isReleaseDay,
  isWeekend,
  isParadoDay,
  getChgDates,
  getWorkingDays,
  createId,
} from "@/utils";
import { COLORS } from "@/styles";
import { calcularTermino, type Pacote } from "@/utils/schedule";
import type { Estimativa } from "@/types";

const DEFAULT_OVERTIME = { tombamentoDates: [] as string[], feriadoDates: [] as string[], fimDeSemanaDates: [] as string[] };

/* ═══════════════════════════════════════════════════════════════════════════
   Date helpers — timezone-safe
   ═══════════════════════════════════════════════════════════════════════════ */

export function extractYMD(dateString: string | undefined): [number, number, number] | null {
  if (!dateString) return null;
  const iso = dateString.match(/^(\d{4})-(\d{2})-(\d{2})/);
  if (iso) return [Number(iso[1]), Number(iso[2]), Number(iso[3])];
  const br = dateString.match(/^(\d{2})\/(\d{2})\/(\d{4})$/);
  if (br) return [Number(br[3]), Number(br[2]), Number(br[1])];
  const d = new Date(dateString);
  if (!Number.isNaN(d.getTime())) return [d.getFullYear(), d.getMonth() + 1, d.getDate()];
  return null;
}

export function makeLocalDate(y: number, m: number, day: number): Date {
  return new Date(y, m - 1, day, 0, 0, 0, 0);
}

export function todayLocal(): Date {
  const n = new Date();
  return new Date(n.getFullYear(), n.getMonth(), n.getDate(), 0, 0, 0, 0);
}

export function formatDateBR(dateInput: string | Date | undefined | null): string {
  if (!dateInput) return "—";
  if (dateInput instanceof Date) {
    if (!isValidDate(dateInput)) return "—";
    const date = makeLocalDate(dateInput.getFullYear(), dateInput.getMonth() + 1, dateInput.getDate());
    return date.toLocaleDateString("pt-BR", { day: "2-digit", month: "2-digit", year: "numeric" });
  }
  if (/^\d{2}\/\d{2}\/\d{4}$/.test(dateInput)) return dateInput;
  const ymd = extractYMD(dateInput);
  if (!ymd) return dateInput;
  const date = makeLocalDate(ymd[0], ymd[1], ymd[2]);
  return date.toLocaleDateString("pt-BR", { day: "2-digit", month: "2-digit", year: "numeric" });
}

export function formatDateRelative(dateString: string | undefined): string {
  if (!dateString) return "";
  const ymd = extractYMD(dateString);
  if (!ymd) return dateString;
  const target = makeLocalDate(ymd[0], ymd[1], ymd[2]);
  const today = todayLocal();
  const diff = Math.round((target.getTime() - today.getTime()) / (1000 * 60 * 60 * 24));
  if (diff === 0) return "Hoje";
  if (diff === 1) return "Amanhã";
  if (diff === -1) return "Ontem";
  if (diff > 1 && diff < 7) {
    const days = ["dom", "seg", "ter", "qua", "qui", "sex", "sáb"];
    return days[target.getDay()];
  }
  return target.toLocaleDateString("pt-BR", { day: "2-digit", month: "2-digit", year: "numeric" });
}

/* ═══════════════════════════════════════════════════════════════════════════
   Task helpers
   ═══════════════════════════════════════════════════════════════════════════ */

export function normalizeTaskType(rawTipo: unknown) {
  const tipo = String(rawTipo || "").trim().toLowerCase();
  if (tipo === "front" || tipo === "micro" || tipo === "desenvolvimento") return "desenvolvimento";
  if (tipo === "subida") return "subida";
  if (tipo === "testes" || tipo === "teste") return "testes";
  return "desenvolvimento";
}

export function isPlaceholderTask(title: string, atividade: any) {
  const normalizedTitle = String(title || "").trim().toLowerCase();
  const titleSegments = normalizedTitle.split(/:/).map((s) => s.trim()).filter(Boolean);
  const titleWithoutPackage = titleSegments.length > 1 ? titleSegments[titleSegments.length - 1] : normalizedTitle;
  const hasNoName = !atividade.nome && !atividade.titulo && !atividade.demanda;
  const hasNoDates = !atividade.inicio && !atividade.dataInicio && !atividade.termino && !atividade.dataFim;
  const isDefaultHours = Number(atividade.horas ?? 0) === 8;
  const isDefaultOvertime = Number(atividade.horasOvertime ?? 0) === 0;
  const isAutoGeneratedTitle = /^tarefa\s+\d+$/i.test(titleWithoutPackage);
  return hasNoName && isAutoGeneratedTitle && hasNoDates && isDefaultHours && isDefaultOvertime;
}

export function getTasksForEstimate(estimate: Estimativa) {
  const tasks: Array<{ id: string; title: string; tipo: string; inicio: string; termino: string; dias?: number }> = [];

  if (Array.isArray(estimate.atividades)) {
    estimate.atividades.forEach((atividade, index) => {
      const title = atividade.nome || atividade.titulo || atividade.demanda || `Tarefa ${index + 1}`;
      if (isPlaceholderTask(title, atividade)) return;
      tasks.push({
        id: atividade.id ?? `atividade-${index}`,
        title,
        tipo: normalizeTaskType(atividade.tipo),
        inicio: atividade.inicio || atividade.dataInicio || "",
        termino: atividade.termino || atividade.dataFim || "",
      });
    });
  }

  if (estimate.tipo === "estimativa-pacotes" && Array.isArray(estimate.pacotes)) {
    estimate.pacotes.forEach((pacote, pacoteIndex) => {
      if (Array.isArray(pacote.atividades)) {
        pacote.atividades.forEach((atividade, index) => {
          const title = `${pacote.nome ? `${pacote.nome}: ` : ""}${atividade.nome || atividade.titulo || atividade.demanda || `Tarefa ${index + 1}`}`;
          if (isPlaceholderTask(title, atividade)) return;
          const workDays = Math.max(1, Math.ceil(Number(atividade.horas || 0) / 8));
          let termino = atividade.termino || atividade.dataFim || "";
          if (!termino && atividade.inicio) {
            termino = calcularTermino(
              atividade.inicio,
              Number(atividade.horas || 0),
              normalizeDateList(estimate.feriados || ""),
              normalizeDateList(estimate.releases || ""),
              atividade.overtime || { tombamentoDates: [], feriadoDates: [], fimDeSemanaDates: [] },
              Number(atividade.horasOvertime || 0),
              parseDiasParadosList(estimate.diasParados || "")
            );
          }
          tasks.push({
            id: atividade.id ?? `pacote-${pacoteIndex}-atividade-${index}`,
            title,
            tipo: normalizeTaskType(atividade.tipo),
            inicio: atividade.inicio || atividade.dataInicio || "",
            termino,
            dias: Number(atividade.dias ?? workDays),
          });
        });
      }
    });
  }

  return tasks.filter((task) => String(task.title || "").trim() !== "" && (task.inicio || task.termino));
}

export function getFlattenedEstimateActivities(estimate: Estimativa) {
  const activities: Array<{ id: string; nome: string; tipo: string; etapa: string; dias: number; inicio: string; termino: string }> = [];

  if (Array.isArray(estimate.atividades)) {
    estimate.atividades.forEach((atividade, index) => {
      activities.push({
        id: atividade.id ?? `atividade-${index}`,
        nome: atividade.nome || atividade.titulo || atividade.demanda || `Atividade ${index + 1}`,
        tipo: normalizeTaskType(atividade.tipo),
        etapa: String(atividade.etapa ?? "1"),
        dias: Number(atividade.dias ?? 0),
        inicio: atividade.inicio || atividade.dataInicio || "",
        termino: atividade.termino || atividade.dataFim || "",
      });
    });
  }

  if (estimate.tipo === "estimativa-pacotes" && Array.isArray(estimate.pacotes)) {
    estimate.pacotes.forEach((pacote) => {
      if (Array.isArray(pacote.atividades)) {
        pacote.atividades.forEach((atividade, index) => {
          const title = `${pacote.nome ? `${pacote.nome}: ` : ""}${atividade.nome || atividade.titulo || atividade.demanda || `Atividade ${index + 1}`}`;
          if (isPlaceholderTask(title, atividade)) return;
          const workDays = Math.max(1, Math.ceil(Number(atividade.horas || 0) / 8));
          activities.push({
            id: atividade.id ?? `pacote-${pacote.id ?? pacote.nome ?? "unknown"}-atividade-${index}`,
            nome: title,
            tipo: normalizeTaskType(atividade.tipo),
            etapa: String(atividade.etapa ?? "1"),
            dias: Number(atividade.dias ?? workDays),
            inicio: atividade.inicio || atividade.dataInicio || "",
            termino: atividade.termino || atividade.dataFim || "",
          });
        });
      }
    });
  }

  return activities;
}

type CalendarDay = { date: Date; tipo: string; color: string; isReleaseDay: boolean; isEsteiraPreProd: boolean; isChg: boolean; workBorderColor?: string };

function buildSpecialWorkDatesMap(
  estimate: Estimativa,
  feriados: string[],
  releases: string[],
  paradoRanges: { start: Date; end: Date }[]
): Record<string, string> {
  const atividadesLegado = Array.isArray(estimate.atividades) ? estimate.atividades : [];
  const pacotes = Array.isArray(estimate.pacotes) ? (estimate.pacotes as Pacote[]) : [];

  const allAtividades: Array<{
    tipo: string;
    inicio: string;
    horas: number;
    horasOvertime?: number;
    overtime?: { tombamentoDates?: string[]; feriadoDates?: string[]; fimDeSemanaDates?: string[] };
  }> = [
    ...atividadesLegado.map((a) => ({
      tipo: normalizeTaskType(a.tipo),
      inicio: a.inicio || a.dataInicio || "",
      horas: Number(a.horas || 0),
      horasOvertime: Number(a.horasOvertime || 0),
      overtime: a.overtime || DEFAULT_OVERTIME,
    })),
    ...pacotes.flatMap((p) =>
      Array.isArray(p.atividades)
        ? p.atividades.map((a) => ({
            tipo: normalizeTaskType(a.tipo),
            inicio: a.inicio || "",
            horas: Number(a.horas || 0),
            horasOvertime: Number(a.horasOvertime || 0),
            overtime: a.overtime || DEFAULT_OVERTIME,
          }))
        : []
    ),
  ];

  return buildSpecialWorkDatesMapFromAtividades(allAtividades, feriados, releases, paradoRanges);
}

function buildSpecialWorkDatesMapFromAtividades(
  atividades: Array<{
    tipo: string;
    inicio: string;
    horas: number;
    horasOvertime?: number;
    overtime?: { tombamentoDates?: string[]; feriadoDates?: string[]; fimDeSemanaDates?: string[] };
  }>,
  feriados: string[],
  releases: string[],
  paradoRanges: { start: Date; end: Date }[]
): Record<string, string> {
  const map: Record<string, string> = {};

  for (const a of atividades) {
    if (!a.inicio || a.horas <= 0) continue;
    const color = getTimelineColor(a.tipo);
    const ot = { ...DEFAULT_OVERTIME, ...(a.overtime || {}) };
    const horasOT = a.horasOvertime ?? 0;
    const terminoStr = calcularTermino(a.inicio, a.horas, feriados, releases, ot, horasOT, paradoRanges);
    const inicioDate = parseDateBR(a.inicio);
    const terminoDate = parseDateBR(terminoStr);
    if (!isValidDate(inicioDate) || !isValidDate(terminoDate)) continue;

    const allDates = [...(ot.feriadoDates || []), ...(ot.fimDeSemanaDates || []), ...(ot.tombamentoDates || [])];
    for (const dateStr of allDates) {
      const parsed = parseDateBR(dateStr);
      if (!isValidDate(parsed)) continue;
      if (parsed < inicioDate || parsed > terminoDate) continue;
      const key = parsed.toISOString().split("T")[0];
      if (!map[key]) map[key] = color;
    }

    const isSpecial = isWeekend(inicioDate) || isHoliday(inicioDate, feriados) || isPostRelease(inicioDate, releases);
    if (isSpecial) {
      const key = inicioDate.toISOString().split("T")[0];
      if (!map[key]) map[key] = color;
    }
  }

  return map;
}

function applyOffsetToSpecialWorkDates(
  map: Record<string, string>,
  offsetDays: number
): Record<string, string> {
  if (offsetDays === 0) return map;
  const result: Record<string, string> = {};
  for (const [key, color] of Object.entries(map)) {
    const date = parseDateBR(key);
    if (!isValidDate(date)) continue;
    const offsetDate = addDays(date, offsetDays);
    const offsetKey = offsetDate.toISOString().split("T")[0];
    result[offsetKey] = color;
  }
  return result;
}

interface ActivityRange {
  id: string;
  nome: string;
  tipo: string;
  etapa: string;
  inicio: Date;
  termino: Date;
  color: string;
}

function getEstimateActivityRanges(
  estimate: Estimativa,
  feriados: string[],
  releases: string[],
  paradoRanges: { start: Date; end: Date }[]
): ActivityRange[] {
  const ranges: ActivityRange[] = [];

  if (Array.isArray(estimate.pacotes)) {
    for (const pacote of estimate.pacotes) {
      if (!Array.isArray(pacote.atividades)) continue;
      for (const a of pacote.atividades) {
        const inicioStr = a.inicio || a.dataInicio;
        if (!inicioStr) continue;
        const horas = Number(a.horas || 0);
        const horasOT = Number(a.horasOvertime || 0);
        const ot = { ...DEFAULT_OVERTIME, ...(a.overtime || {}) };
        const terminoStr = calcularTermino(inicioStr, horas, feriados, releases, ot, horasOT, paradoRanges);
        const inicioDate = parseDateBR(inicioStr);
        const terminoDate = parseDateBR(terminoStr);
        if (!isValidDate(inicioDate) || !isValidDate(terminoDate)) continue;
        const tipo = normalizeTaskType(a.tipo);
        ranges.push({
          id: a.id ?? createId(),
          nome: `${pacote.nome ? `${pacote.nome}: ` : ""}${a.nome || a.titulo || a.demanda || ""}`,
          tipo,
          etapa: String(a.etapa || "1"),
          inicio: inicioDate,
          termino: terminoDate,
          color: getTimelineColor(tipo),
        });
      }
    }
  }

  if (Array.isArray(estimate.atividades)) {
    for (const a of estimate.atividades) {
      const inicioStr = a.inicio || a.dataInicio;
      const terminoStr = a.termino || a.dataFim;
      const inicioDate = parseDateBR(inicioStr);
      const terminoDate = parseDateBR(terminoStr);
      if (!isValidDate(inicioDate) || !isValidDate(terminoDate)) continue;
      const tipo = normalizeTaskType(a.tipo);
      ranges.push({
        id: a.id ?? createId(),
        nome: a.nome || a.titulo || a.demanda || "",
        tipo,
        etapa: String(a.etapa || "1"),
        inicio: inicioDate,
        termino: terminoDate,
        color: getTimelineColor(tipo),
      });
    }
  }

  return ranges;
}

export interface RealCalendarResult {
  rows: Array<Array<CalendarDay | null>>;
  rangeStart: Date | null;
  rangeEnd: Date | null;
  calculatedEndDate: Date | null;
  atividadesCalculadas: Array<{ id: string; nome: string; tipo: string; etapa: string; dias: number; inicio: Date; termino: Date }>;
}

export function buildRealCalendar(
  estimate: Estimativa,
  dataRealInicio: string | undefined,
  diasImpactados: string | undefined,
  chgDias: number | string | undefined,
  esteiraPreProd: string | undefined,
  feriadosExternos?: string[],
  releasesExternos?: string[],
  realSchedule?: Pacote[],
  realProductionDate?: string
): RealCalendarResult {
  const empty: RealCalendarResult = { rows: [], rangeStart: null, rangeEnd: null, calculatedEndDate: null, atividadesCalculadas: [] };
  if (!dataRealInicio) return empty;

  const holidayDates = feriadosExternos ?? normalizeDateList(estimate.feriados || "");
  const releaseDates = releasesExternos ?? normalizeDateList(estimate.releases || "");
  const preprodRanges = parseDateRangeList(esteiraPreProd || "");
  const paradaRanges = parseDiasParadosList(diasImpactados || "");
  const productionDateStr = realProductionDate || estimate.releaseAlvo;
  const releaseDate = productionDateStr ? parseDateBR(productionDateStr) : new Date(NaN);
  const chgDates = getChgDates(releaseDate, Number(chgDias || 0), holidayDates);
  const realStartDate = parseDateBR(dataRealInicio);
  if (!isValidDate(realStartDate)) return empty;

  let realRanges: ActivityRange[];
  let realSpecialWorkDates: Record<string, string>;

  if (realSchedule && realSchedule.length > 0) {
    realRanges = getRealActivityRanges(realSchedule, holidayDates, releaseDates, paradaRanges);
    realSpecialWorkDates = buildSpecialWorkDatesMapFromAtividades(
      realSchedule.flatMap((p) =>
        Array.isArray(p.atividades)
          ? p.atividades.map((a) => ({
              tipo: normalizeTaskType(a.tipo),
              inicio: a.inicio || "",
              horas: Number(a.horas || 0),
              horasOvertime: Number(a.horasOvertime || 0),
              overtime: a.overtime || DEFAULT_OVERTIME,
            }))
          : []
      ),
      holidayDates,
      releaseDates,
      paradaRanges
    );
  } else {
    const specialWorkDates = buildSpecialWorkDatesMap(estimate, holidayDates, releaseDates, paradaRanges);
    const estimateRanges = getEstimateActivityRanges(estimate, holidayDates, releaseDates, paradaRanges);
    const estimateStartDates = estimateRanges.map((a) => a.inicio).filter(isValidDate);
    if (estimateStartDates.length === 0) return empty;
    const estimateStartDate = new Date(Math.min(...estimateStartDates.map((d) => d.getTime())));
    const offsetDays = Math.round((realStartDate.getTime() - estimateStartDate.getTime()) / (1000 * 60 * 60 * 24));

    realRanges = estimateRanges.map((a) => ({
      ...a,
      inicio: addDays(a.inicio, offsetDays),
      termino: addDays(a.termino, offsetDays),
    }));

    realSpecialWorkDates = applyOffsetToSpecialWorkDates(specialWorkDates, offsetDays);
  }

  const calculatedEndDate = new Date(Math.max(...realRanges.map((a) => a.termino.getTime())));
  const endDate = isValidDate(releaseDate) && releaseDate > calculatedEndDate ? releaseDate : calculatedEndDate;

  const timeline: Array<CalendarDay> = [];
  let current = new Date(realStartDate);

  while (current <= endDate) {
    const date = new Date(current);
    let tipo = "";
    let color = COLORS.white;

    if (isValidDate(releaseDate) && sameDateBR(date, releaseDate)) {
      tipo = "Release alvo";
      color = COLORS.releaseTarget;
    } else if (isParadoDay(date, paradaRanges, holidayDates, releaseDates)) {
      tipo = "Projeto impactado";
      color = COLORS.blocked;
    } else if (isWeekend(date)) {
      tipo = "Fim de semana";
      color = COLORS.weekend;
    } else if (isHoliday(date, holidayDates)) {
      tipo = "Feriado";
      color = COLORS.holiday;
    } else if (isPostRelease(date, releaseDates)) {
      tipo = "Tombamento";
      color = COLORS.postRelease;
    } else {
      const activity = realRanges.find((item) => date >= item.inicio && date <= item.termino);
      if (activity) {
        tipo = getTimelineLabel(activity.tipo, activity.nome);
        color = activity.color;
      }
    }

    const dateKey = date.toISOString().split("T")[0];
    timeline.push({ date, tipo, color, isReleaseDay: isReleaseDay(date, releaseDates), isEsteiraPreProd: isEsteiraPreProdDay(date, preprodRanges), isChg: chgDates.some((d) => sameDateBR(d, date)), workBorderColor: realSpecialWorkDates[dateKey] });
    current = addDays(current, 1);
  }

  const rows: Array<Array<CalendarDay | null>> = [];
  const blockSize = 15;
  for (let index = 0; index < timeline.length; index += blockSize) {
    const row = timeline.slice(index, index + blockSize);
    while (row.length < blockSize) row.push(null);
    rows.push(row);
  }

  return { rows, rangeStart: realStartDate, rangeEnd: endDate, calculatedEndDate, atividadesCalculadas: realRanges.map((a) => ({ ...a, dias: 0 })) };
}

function getRealActivityRanges(
  pacotes: Pacote[],
  feriados: string[],
  releases: string[],
  paradoRanges: { start: Date; end: Date }[]
): ActivityRange[] {
  const ranges: ActivityRange[] = [];
  for (const pacote of pacotes) {
    if (!Array.isArray(pacote.atividades)) continue;
    for (const a of pacote.atividades) {
      const inicioStr = a.inicio || "";
      if (!inicioStr) continue;
      const horas = Number(a.horas || 0);
      const horasOT = Number(a.horasOvertime || 0);
      const ot = { ...DEFAULT_OVERTIME, ...(a.overtime || {}) };
      const terminoStr = calcularTermino(inicioStr, horas, feriados, releases, ot, horasOT, paradoRanges);
      const inicioDate = parseDateBR(inicioStr);
      const terminoDate = parseDateBR(terminoStr);
      if (!isValidDate(inicioDate) || !isValidDate(terminoDate)) continue;
      const tipo = normalizeTaskType(a.tipo);
      ranges.push({
        id: a.id,
        nome: `${pacote.nome ? `${pacote.nome}: ` : ""}${a.nome || a.demanda || ""}`,
        tipo,
        etapa: String(a.etapa || "1"),
        inicio: inicioDate,
        termino: terminoDate,
        color: getTimelineColor(tipo),
      });
    }
  }
  return ranges;
}

export function diffDiasCorridos(data1: string | Date | undefined, data2: string | Date | undefined): number | null {
  const d1 = typeof data1 === "string" ? parseDateBR(data1) : data1;
  const d2 = typeof data2 === "string" ? parseDateBR(data2) : data2;
  if (!d1 || !d2 || !isValidDate(d1) || !isValidDate(d2)) return null;
  return Math.round((d2.getTime() - d1.getTime()) / (1000 * 60 * 60 * 24));
}

export interface EstimateCalendarResult {
  rows: Array<Array<CalendarDay | null>>;
  rangeStart: Date | null;
  rangeEnd: Date | null;
  calculatedEndDate: Date | null;
  atividadesCalculadas: Array<{ id: string; nome: string; tipo: string; etapa: string; dias: number; inicio: Date; termino: Date }>;
}

export function buildEstimateCalendar(estimate: Estimativa): EstimateCalendarResult {
  const empty: EstimateCalendarResult = { rows: [], rangeStart: null, rangeEnd: null, calculatedEndDate: null, atividadesCalculadas: [] };
  const holidayDates = normalizeDateList(estimate.feriados || "");
  const releaseDates = normalizeDateList(estimate.releases || "");
  const preprodRanges = parseDateRangeList(estimate.esteiraPreProd || "");
  const paradaRanges = parseDiasParadosList(estimate.diasParados || "");
  const releaseDate = estimate.releaseAlvo ? parseDateBR(estimate.releaseAlvo) : new Date(NaN);
  const chgDates = getChgDates(releaseDate, Number(estimate.chgDias || 0), holidayDates);
  const specialWorkDates = buildSpecialWorkDatesMap(estimate, holidayDates, releaseDates, paradaRanges);

  const activityRanges = getEstimateActivityRanges(estimate, holidayDates, releaseDates, paradaRanges);
  const startDates = activityRanges.map((a) => a.inicio).filter(isValidDate);
  if (startDates.length === 0) return empty;

  const startDate = new Date(Math.min(...startDates.map((d) => d.getTime())));
  const calculatedEndDate = new Date(Math.max(...activityRanges.map((a) => a.termino.getTime())));
  const endDate = isValidDate(releaseDate) && releaseDate > calculatedEndDate ? releaseDate : calculatedEndDate;

  const timeline: Array<CalendarDay> = [];
  let current = new Date(startDate);

  while (current <= endDate) {
    const date = new Date(current);
    let tipo = "";
    let color = COLORS.white;

    if (isValidDate(releaseDate) && sameDateBR(date, releaseDate)) {
      tipo = "Release alvo";
      color = COLORS.releaseTarget;
    } else if (isParadoDay(date, paradaRanges, holidayDates, releaseDates)) {
      tipo = "Projeto impactado";
      color = COLORS.blocked;
    } else if (isWeekend(date)) {
      tipo = "Fim de semana";
      color = COLORS.weekend;
    } else if (isHoliday(date, holidayDates)) {
      tipo = "Feriado";
      color = COLORS.holiday;
    } else if (isPostRelease(date, releaseDates)) {
      tipo = "Tombamento";
      color = COLORS.postRelease;
    } else {
      const activity = activityRanges.find((item) => date >= item.inicio && date <= item.termino);
      if (activity) {
        tipo = getTimelineLabel(activity.tipo, activity.nome);
        color = activity.color;
      }
    }

    const dateKey = date.toISOString().split("T")[0];
    timeline.push({ date, tipo, color, isReleaseDay: isReleaseDay(date, releaseDates), isEsteiraPreProd: isEsteiraPreProdDay(date, preprodRanges), isChg: chgDates.some((d) => sameDateBR(d, date)), workBorderColor: specialWorkDates[dateKey] });
    current = addDays(current, 1);
  }

  const rows: Array<Array<CalendarDay | null>> = [];
  const blockSize = 15;
  for (let index = 0; index < timeline.length; index += blockSize) {
    const row = timeline.slice(index, index + blockSize);
    while (row.length < blockSize) row.push(null);
    rows.push(row);
  }

  return { rows, rangeStart: startDate, rangeEnd: endDate, calculatedEndDate, atividadesCalculadas: activityRanges.map((a) => ({ ...a, dias: 0 })) };
}

/* ═══════════════════════════════════════════════════════════════════════════
   Task counting helpers
   ═══════════════════════════════════════════════════════════════════════════ */

export function countTasks(tasks: KanbanCustomTask[] | undefined): number {
  if (!tasks) return 0;
  return tasks.reduce((count, task) => count + 1 + countTasks(task.subtasks), 0);
}

export function countCompleted(tasks: KanbanCustomTask[] | undefined): number {
  if (!tasks) return 0;
  return tasks.reduce((count, task) => count + (task.completed ? 1 : 0) + countCompleted(task.subtasks), 0);
}

export function taskProgressPercent(tasks: KanbanCustomTask[] | undefined): number {
  const total = countTasks(tasks);
  if (!total) return 0;
  return Math.round((countCompleted(tasks) / total) * 100);
}

export function findTaskInTree(tasks: KanbanCustomTask[] | undefined, taskId: string): KanbanCustomTask | null {
  if (!tasks) return null;
  for (const task of tasks) {
    if (task.id === taskId) return task;
    const found = findTaskInTree(task.subtasks, taskId);
    if (found) return found;
  }
  return null;
}

export function getTaskPath(tasks: KanbanCustomTask[] | undefined, taskId: string): KanbanCustomTask[] {
  if (!tasks) return [];
  for (const task of tasks) {
    if (task.id === taskId) return [task];
    const subPath = getTaskPath(task.subtasks, taskId);
    if (subPath.length) return [task, ...subPath];
  }
  return [];
}

/* ═══════════════════════════════════════════════════════════════════════════
   Priority helpers
   ═══════════════════════════════════════════════════════════════════════════ */

export const PRIORITY_CONFIG: Record<TaskPriority, { label: string; color: string; bg: string; border: string }> = {
  p1: { label: "Prioridade 1", color: "text-red-400", bg: "bg-red-400/10", border: "border-red-400/30" },
  p2: { label: "Prioridade 2", color: "text-orange-400", bg: "bg-orange-400/10", border: "border-orange-400/30" },
  p3: { label: "Prioridade 3", color: "text-blue-400", bg: "bg-blue-400/10", border: "border-blue-400/30" },
  p4: { label: "Prioridade 4", color: "text-muted-foreground", bg: "bg-muted", border: "border-border" },
};

export const PRIORITY_CONFIG_SIMPLE: Record<TaskPriority, { color: string }> = {
  p1: { color: "text-red-400" },
  p2: { color: "text-orange-400" },
  p3: { color: "text-blue-400" },
  p4: { color: "text-muted-foreground" },
};

export function getCardProgress(
  card: KanbanCard,
  estimateTasks: Array<{ id: string }>
): { total: number; completed: number; percent: number } {
  const customTotal = countTasks(card.tasks);
  const customCompleted = countCompleted(card.tasks);
  const estimateTotal = estimateTasks.length;
  const estimateCompleted =
    card.completedEstimateTaskIds?.filter((id) => estimateTasks.some((t) => t.id === id)).length ?? 0;
  const total = customTotal + estimateTotal;
  const completed = customCompleted + estimateCompleted;
  return { total, completed, percent: total > 0 ? Math.round((completed / total) * 100) : 0 };
}

/* ═══════════════════════════════════════════════════════════════════════════
   Estimated vs Real schedule comparison + CHG window alert
   ═══════════════════════════════════════════════════════════════════════════ */

export type CompareStatus = "ok" | "warning" | "critical";

export function getEstimatedStartDate(estimate: Estimativa): Date | null {
  const activities = getFlattenedEstimateActivities(estimate);
  const activityStarts = activities
    .map((a) => parseDateBR(a.inicio))
    .filter(isValidDate);
  if (activityStarts.length > 0) {
    return new Date(Math.min(...activityStarts.map((d) => d.getTime())));
  }
  const fallback = parseDateBR(estimate.inicio);
  return isValidDate(fallback) ? fallback : null;
}

export function getEstimatedEndDate(
  estimate: Estimativa,
  feriados: string[] = [],
  releases: string[] = [],
  diasParados?: string
): Date | null {
  const paradoRanges = parseDiasParadosList(diasParados ?? estimate.diasParados ?? "");

  // Para estimativas por pacotes o termino é calculado a partir de inicio + horas.
  const ranges = getEstimateActivityRanges(estimate, feriados, releases, paradoRanges);
  if (ranges.length > 0) {
    return new Date(Math.max(...ranges.map((r) => r.termino.getTime())));
  }

  // Fallback para atividades legado que possuem termino explícito.
  const activities = getFlattenedEstimateActivities(estimate);
  const activityEnds = activities
    .map((a) => parseDateBR(a.termino))
    .filter(isValidDate);
  if (activityEnds.length > 0) {
    return new Date(Math.max(...activityEnds.map((d) => d.getTime())));
  }

  return null;
}

export function calcChgWindow(
  productionDate: Date | string | undefined,
  chgDays: number | string | undefined,
  holidays: string[]
): { start: Date; end: Date } | null {
  const prodDate = typeof productionDate === "string" ? parseDateBR(productionDate) : productionDate;
  const total = Number(chgDays || 0);
  if (!isValidDate(prodDate) || total <= 0) return null;

  const chgDates = getChgDates(prodDate, total, holidays);
  if (chgDates.length === 0) return null;

  return {
    start: chgDates[chgDates.length - 1],
    end: chgDates[0],
  };
}

export function getChgImpactStatus(
  realEnd: Date | string | undefined,
  productionDate: Date | string | undefined,
  chgWindow: { start: Date; end: Date } | null
): { status: CompareStatus; message: string; detail?: string } {
  const realEndDate = typeof realEnd === "string" ? parseDateBR(realEnd) : realEnd;
  const prodDate = typeof productionDate === "string" ? parseDateBR(productionDate) : productionDate;

  if (!isValidDate(realEndDate) || !isValidDate(prodDate)) {
    return { status: "ok", message: "" };
  }

  // Critical: real end after production date
  if (realEndDate > prodDate) {
    return {
      status: "critical",
      message: "Crítico: produção em risco",
      detail: "O término real previsto ocorre após a data planejada de subida em produção. Replaneje a data de produção.",
    };
  }

  // Warning: real end inside CHG window
  if (chgWindow && realEndDate >= chgWindow.start && realEndDate <= chgWindow.end) {
    return {
      status: "warning",
      message: "Atenção: janela de CHG comprometida",
      detail: "O término real previsto invade o período necessário para trâmite de CHG. A data de subida em produção pode precisar ser alterada.",
    };
  }

  // Warning: not enough working days between real end and production
  if (chgWindow && realEndDate < chgWindow.start) {
    return {
      status: "ok",
      message: "Dentro do prazo",
      detail: "O término real previsto permite cumprir o trâmite de CHG antes da produção.",
    };
  }

  return { status: "ok", message: "Dentro do prazo" };
}

export interface ScheduleComparisonResult {
  estimatedStart: Date | null;
  estimatedEnd: Date | null;
  productionDate: Date | null;
  realProductionDate: Date | null;
  realStart: Date | null;
  realEnd: Date | null;
  diffStartDays: number | null;
  diffEndDays: number | null;
  diffRealEndProductionDays: number | null;
  chgWindow: { start: Date; end: Date } | null;
  chgStatus: CompareStatus;
  chgMessage: string;
  chgDetail?: string;
}

export function calcScheduleComparison(
  estimate: Estimativa,
  card: KanbanCard,
  realEnd: Date | string | undefined,
  holidays: string[],
  releases: string[] = []
): ScheduleComparisonResult {
  const estimatedStart = getEstimatedStartDate(estimate);
  const estimatedEnd = getEstimatedEndDate(estimate, holidays, releases, estimate.diasParados);
  const productionDate = parseDateBR(estimate.releaseAlvo);
  const realProductionDate = parseDateBR(card.realProductionDate ?? estimate.releaseAlvo);
  const realStart = parseDateBR(card.dataRealInicio);
  const realEndDate = typeof realEnd === "string" ? parseDateBR(realEnd) : realEnd;

  const diffStartDays =
    isValidDate(estimatedStart) && isValidDate(realStart)
      ? Math.round((realStart.getTime() - estimatedStart.getTime()) / (1000 * 60 * 60 * 24))
      : null;

  const diffEndDays =
    isValidDate(estimatedEnd) && isValidDate(realEndDate)
      ? Math.round((realEndDate.getTime() - estimatedEnd.getTime()) / (1000 * 60 * 60 * 24))
      : null;

  const diffRealEndProductionDays =
    isValidDate(realEndDate) && isValidDate(realProductionDate)
      ? Math.round((realEndDate.getTime() - realProductionDate.getTime()) / (1000 * 60 * 60 * 24))
      : null;

  const chgWindow = isValidDate(realProductionDate)
    ? calcChgWindow(realProductionDate, card.chgDias ?? estimate.chgDias ?? 0, holidays)
    : null;

  const { status, message, detail } = getChgImpactStatus(realEndDate, realProductionDate, chgWindow);

  return {
    estimatedStart,
    estimatedEnd,
    productionDate: isValidDate(productionDate) ? productionDate : null,
    realProductionDate: isValidDate(realProductionDate) ? realProductionDate : null,
    realStart: isValidDate(realStart) ? realStart : null,
    realEnd: isValidDate(realEndDate) ? realEndDate : null,
    diffStartDays,
    diffEndDays,
    diffRealEndProductionDays,
    chgWindow,
    chgStatus: status,
    chgMessage: message,
    chgDetail: detail,
  };
}

export function formatDiffDays(days: number | null | undefined): string {
  if (days === null || days === undefined) return "—";
  if (days === 0) return "0 dias";
  if (days > 0) return `+${days} dias (atraso)`;
  return `${days} dias (adiantamento)`;
}

export function formatChgWindow(window: { start: Date; end: Date } | null | undefined): string {
  if (!window) return "—";
  return `${formatDateBR(window.start)} até ${formatDateBR(window.end)}`;
}
