import type { KanbanCustomTask, TaskPriority } from "@/types";
import {
  parseDateBR,
  isValidDate,
  sameDateBR,
  addDays,
  parseDateRangeList,
  parseDiasParadosList,
  normalizeDateList,
  getTimelineColor,
  getTimelineLabel,
  isEsteiraPreProdDay,
  isHoliday,
  isPostRelease,
  isReleaseDay,
  isWeekend,
  isParadoDay,
  getChgDates,
  getWorkingDays,
} from "@/utils";
import { COLORS } from "@/styles";
import { calcularTermino } from "@/components/estimativa-pacotes";
import type { Estimativa } from "@/types";

/* ═══════════════════════════════════════════════════════════════════════════
   Date helpers — timezone-safe
   ═══════════════════════════════════════════════════════════════════════════ */

export function extractYMD(dateString: string | undefined): [number, number, number] | null {
  if (!dateString) return null;
  const iso = dateString.match(/^(\d{4})-(\d{2})-(\d{2})/);
  if (iso) return [Number(iso[1]), Number(iso[2]), Number(iso[3])];
  const br = dateString.match(/^(\d{2})\/(\d{2})\/(\d{4})$/);
  if (br) return [Number(br[3]), Number(br[2]), Number(br[1])];
  const d = new Date(dateString);
  if (!Number.isNaN(d.getTime())) return [d.getFullYear(), d.getMonth() + 1, d.getDate()];
  return null;
}

export function makeLocalDate(y: number, m: number, day: number): Date {
  return new Date(y, m - 1, day, 0, 0, 0, 0);
}

export function todayLocal(): Date {
  const n = new Date();
  return new Date(n.getFullYear(), n.getMonth(), n.getDate(), 0, 0, 0, 0);
}

export function formatDateBR(dateString: string | undefined): string {
  if (!dateString) return "—";
  if (/^\d{2}\/\d{2}\/\d{4}$/.test(dateString)) return dateString;
  const ymd = extractYMD(dateString);
  if (!ymd) return dateString;
  const date = makeLocalDate(ymd[0], ymd[1], ymd[2]);
  return date.toLocaleDateString("pt-BR", { day: "2-digit", month: "2-digit", year: "numeric" });
}

export function formatDateRelative(dateString: string | undefined): string {
  if (!dateString) return "";
  const ymd = extractYMD(dateString);
  if (!ymd) return dateString;
  const target = makeLocalDate(ymd[0], ymd[1], ymd[2]);
  const today = todayLocal();
  const diff = Math.round((target.getTime() - today.getTime()) / (1000 * 60 * 60 * 24));
  if (diff === 0) return "Hoje";
  if (diff === 1) return "Amanhã";
  if (diff === -1) return "Ontem";
  if (diff > 1 && diff < 7) {
    const days = ["dom", "seg", "ter", "qua", "qui", "sex", "sáb"];
    return days[target.getDay()];
  }
  return target.toLocaleDateString("pt-BR", { day: "numeric", month: "short" });
}

/* ═══════════════════════════════════════════════════════════════════════════
   Task helpers
   ═══════════════════════════════════════════════════════════════════════════ */

export function normalizeTaskType(rawTipo: unknown) {
  const tipo = String(rawTipo || "").trim().toLowerCase();
  if (tipo === "front" || tipo === "micro" || tipo === "desenvolvimento") return "desenvolvimento";
  if (tipo === "subida") return "subida";
  if (tipo === "testes" || tipo === "teste") return "testes";
  return "desenvolvimento";
}

export function isPlaceholderTask(title: string, atividade: any) {
  const normalizedTitle = String(title || "").trim().toLowerCase();
  const titleSegments = normalizedTitle.split(/:/).map((s) => s.trim()).filter(Boolean);
  const titleWithoutPackage = titleSegments.length > 1 ? titleSegments[titleSegments.length - 1] : normalizedTitle;
  const hasNoName = !atividade.nome && !atividade.titulo && !atividade.demanda;
  const hasNoDates = !atividade.inicio && !atividade.dataInicio && !atividade.termino && !atividade.dataFim;
  const isDefaultHours = Number(atividade.horas ?? 0) === 8;
  const isDefaultOvertime = Number(atividade.horasOvertime ?? 0) === 0;
  const isAutoGeneratedTitle = /^tarefa\s+\d+$/i.test(titleWithoutPackage);
  return hasNoName && isAutoGeneratedTitle && hasNoDates && isDefaultHours && isDefaultOvertime;
}

export function getTasksForEstimate(estimate: Estimativa) {
  const tasks: Array<{ id: string; title: string; tipo: string; inicio: string; termino: string; dias?: number }> = [];

  if (Array.isArray(estimate.atividades)) {
    estimate.atividades.forEach((atividade, index) => {
      const title = atividade.nome || atividade.titulo || atividade.demanda || `Tarefa ${index + 1}`;
      if (isPlaceholderTask(title, atividade)) return;
      tasks.push({
        id: atividade.id ?? `atividade-${index}`,
        title,
        tipo: normalizeTaskType(atividade.tipo),
        inicio: atividade.inicio || atividade.dataInicio || "",
        termino: atividade.termino || atividade.dataFim || "",
      });
    });
  }

  if (estimate.tipo === "estimativa-pacotes" && Array.isArray(estimate.pacotes)) {
    estimate.pacotes.forEach((pacote, pacoteIndex) => {
      if (Array.isArray(pacote.atividades)) {
        pacote.atividades.forEach((atividade, index) => {
          const title = `${pacote.nome ? `${pacote.nome}: ` : ""}${atividade.nome || atividade.titulo || atividade.demanda || `Tarefa ${index + 1}`}`;
          if (isPlaceholderTask(title, atividade)) return;
          const workDays = Math.max(1, Math.ceil(Number(atividade.horas || 0) / 8));
          let termino = atividade.termino || atividade.dataFim || "";
          if (!termino && atividade.inicio) {
            termino = calcularTermino(
              atividade.inicio,
              Number(atividade.horas || 0),
              normalizeDateList(estimate.feriados || ""),
              normalizeDateList(estimate.releases || ""),
              atividade.overtime || { tombamentoDates: [], feriadoDates: [], fimDeSemanaDates: [] },
              Number(atividade.horasOvertime || 0),
              parseDiasParadosList(estimate.diasParados || "")
            );
          }
          tasks.push({
            id: atividade.id ?? `pacote-${pacoteIndex}-atividade-${index}`,
            title,
            tipo: normalizeTaskType(atividade.tipo),
            inicio: atividade.inicio || atividade.dataInicio || "",
            termino,
            dias: Number(atividade.dias ?? workDays),
          });
        });
      }
    });
  }

  return tasks.filter((task) => String(task.title || "").trim() !== "" && (task.inicio || task.termino));
}

export function getFlattenedEstimateActivities(estimate: Estimativa) {
  const activities: Array<{ id: string; nome: string; tipo: string; etapa: string; dias: number; inicio: string; termino: string }> = [];

  if (Array.isArray(estimate.atividades)) {
    estimate.atividades.forEach((atividade, index) => {
      activities.push({
        id: atividade.id ?? `atividade-${index}`,
        nome: atividade.nome || atividade.titulo || atividade.demanda || `Atividade ${index + 1}`,
        tipo: normalizeTaskType(atividade.tipo),
        etapa: String(atividade.etapa ?? "1"),
        dias: Number(atividade.dias ?? 0),
        inicio: atividade.inicio || atividade.dataInicio || "",
        termino: atividade.termino || atividade.dataFim || "",
      });
    });
  }

  if (estimate.tipo === "estimativa-pacotes" && Array.isArray(estimate.pacotes)) {
    estimate.pacotes.forEach((pacote) => {
      if (Array.isArray(pacote.atividades)) {
        pacote.atividades.forEach((atividade, index) => {
          const title = `${pacote.nome ? `${pacote.nome}: ` : ""}${atividade.nome || atividade.titulo || atividade.demanda || `Atividade ${index + 1}`}`;
          if (isPlaceholderTask(title, atividade)) return;
          const workDays = Math.max(1, Math.ceil(Number(atividade.horas || 0) / 8));
          activities.push({
            id: atividade.id ?? `pacote-${pacote.id ?? pacote.nome ?? "unknown"}-atividade-${index}`,
            nome: title,
            tipo: normalizeTaskType(atividade.tipo),
            etapa: String(atividade.etapa ?? "1"),
            dias: Number(atividade.dias ?? workDays),
            inicio: atividade.inicio || atividade.dataInicio || "",
            termino: atividade.termino || atividade.dataFim || "",
          });
        });
      }
    });
  }

  return activities;
}

export function buildEstimateCalendar(estimate: Estimativa) {
  const activities = getFlattenedEstimateActivities(estimate);
  const holidayDates = normalizeDateList(estimate.feriados || "");
  const releaseDates = normalizeDateList(estimate.releases || "");
  const preprodRanges = parseDateRangeList(estimate.esteiraPreProd || "");
  const paradaRanges = parseDiasParadosList(estimate.diasParados || "");
  const releaseDate = estimate.releaseAlvo ? parseDateBR(estimate.releaseAlvo) : new Date(NaN);
  const chgDates = getChgDates(releaseDate, Number(estimate.chgDias || 0), holidayDates);

  const startDate = estimate.inicio ? parseDateBR(estimate.inicio) : new Date(NaN);
  if (!isValidDate(startDate)) {
    return { rows: [] as Array<Array<any>>, rangeStart: null as Date | null, rangeEnd: null as Date | null };
  }

  const etapasOrdenadas = Array.from(new Set(activities.map((a) => String(a.etapa || "1")))).sort((a, b) => Number(a) - Number(b));
  const stageDurations = etapasOrdenadas.map((etapa) => {
    const activitiesOfStage = activities.filter((a) => String(a.etapa || "1") === etapa);
    return Math.max(...activitiesOfStage.map((a) => Number(a.dias || 0)));
  });

  const totalDias = stageDurations.reduce((acc, dias) => acc + dias, 0);
  const validDays = getWorkingDays(startDate, totalDias, releaseDates, holidayDates, paradaRanges);

  let cursor = 0;
  const atividadesCalculadas: Array<{ id: string; nome: string; tipo: string; etapa: string; dias: number; inicio: Date; termino: Date }> = [];

  etapasOrdenadas.forEach((etapa, index) => {
    const activitiesOfStage = activities.filter((a) => String(a.etapa || "1") === etapa);
    const inicioEtapa = validDays[cursor];
    activitiesOfStage.forEach((atividade) => {
      const dias = Number(atividade.dias || 0);
      const termino = validDays[cursor + dias - 1];
      if (isValidDate(inicioEtapa) && isValidDate(termino)) {
        atividadesCalculadas.push({ ...atividade, inicio: inicioEtapa, termino });
      }
    });
    cursor += stageDurations[index] || 0;
  });

  const calculatedEndDate = validDays[validDays.length - 1];
  const endDate = isValidDate(releaseDate) && releaseDate > calculatedEndDate ? releaseDate : calculatedEndDate;

  type TimelineDay = { date: Date; tipo: string; color: string; isReleaseDay: boolean; isEsteiraPreProd: boolean; isChg: boolean };
  const timeline: Array<TimelineDay> = [];
  let current = new Date(startDate);

  while (current <= endDate) {
    const date = new Date(current);
    let tipo = "";
    let color = COLORS.white;

    if (isValidDate(releaseDate) && sameDateBR(date, releaseDate)) {
      tipo = "Release alvo";
      color = COLORS.releaseTarget;
    } else if (isParadoDay(date, paradaRanges, holidayDates, releaseDates)) {
      tipo = "Projeto parado";
      color = COLORS.blocked;
    } else if (isWeekend(date)) {
      tipo = "Fim de semana";
      color = COLORS.weekend;
    } else if (isHoliday(date, holidayDates)) {
      tipo = "Feriado";
      color = COLORS.holiday;
    } else if (isPostRelease(date, releaseDates)) {
      tipo = "Tombamento";
      color = COLORS.postRelease;
    } else {
      const activity = atividadesCalculadas.find((item) => isValidDate(item.inicio) && isValidDate(item.termino) && date >= item.inicio && date <= item.termino);
      if (activity) {
        tipo = getTimelineLabel(activity.tipo, activity.nome);
        color = getTimelineColor(activity.tipo);
      }
    }

    timeline.push({ date, tipo, color, isReleaseDay: isReleaseDay(date, releaseDates), isEsteiraPreProd: isEsteiraPreProdDay(date, preprodRanges), isChg: chgDates.some((d) => sameDateBR(d, date)) });
    current = addDays(current, 1);
  }

  const rows: Array<Array<TimelineDay | null>> = [];
  const blockSize = 15;
  for (let index = 0; index < timeline.length; index += blockSize) {
    const row = timeline.slice(index, index + blockSize);
    while (row.length < blockSize) row.push(null);
    rows.push(row);
  }

  return { rows, rangeStart: startDate, rangeEnd: endDate };
}

/* ═══════════════════════════════════════════════════════════════════════════
   Task counting helpers
   ═══════════════════════════════════════════════════════════════════════════ */

export function countTasks(tasks: KanbanCustomTask[] | undefined): number {
  if (!tasks) return 0;
  return tasks.reduce((count, task) => count + 1 + countTasks(task.subtasks), 0);
}

export function countCompleted(tasks: KanbanCustomTask[] | undefined): number {
  if (!tasks) return 0;
  return tasks.reduce((count, task) => count + (task.completed ? 1 : 0) + countCompleted(task.subtasks), 0);
}

export function taskProgressPercent(tasks: KanbanCustomTask[] | undefined): number {
  const total = countTasks(tasks);
  if (!total) return 0;
  return Math.round((countCompleted(tasks) / total) * 100);
}

export function findTaskInTree(tasks: KanbanCustomTask[] | undefined, taskId: string): KanbanCustomTask | null {
  if (!tasks) return null;
  for (const task of tasks) {
    if (task.id === taskId) return task;
    const found = findTaskInTree(task.subtasks, taskId);
    if (found) return found;
  }
  return null;
}

export function getTaskPath(tasks: KanbanCustomTask[] | undefined, taskId: string): KanbanCustomTask[] {
  if (!tasks) return [];
  for (const task of tasks) {
    if (task.id === taskId) return [task];
    const subPath = getTaskPath(task.subtasks, taskId);
    if (subPath.length) return [task, ...subPath];
  }
  return [];
}

/* ═══════════════════════════════════════════════════════════════════════════
   Priority helpers
   ═══════════════════════════════════════════════════════════════════════════ */

export const PRIORITY_CONFIG: Record<TaskPriority, { label: string; color: string; bg: string; border: string }> = {
  p1: { label: "Prioridade 1", color: "text-red-400", bg: "bg-red-400/10", border: "border-red-400/30" },
  p2: { label: "Prioridade 2", color: "text-orange-400", bg: "bg-orange-400/10", border: "border-orange-400/30" },
  p3: { label: "Prioridade 3", color: "text-blue-400", bg: "bg-blue-400/10", border: "border-blue-400/30" },
  p4: { label: "Prioridade 4", color: "text-muted-foreground", bg: "bg-muted", border: "border-border" },
};

export const PRIORITY_CONFIG_SIMPLE: Record<TaskPriority, { color: string }> = {
  p1: { color: "text-red-400" },
  p2: { color: "text-orange-400" },
  p3: { color: "text-blue-400" },
  p4: { color: "text-muted-foreground" },
};
