import type { CSSProperties } from "react";
type PdfStyles = Record<string, CSSProperties>;
export const COLORS = {
  desenvolvimento: "#10b981",
  subida: "#8b5cf6",
  testes: "#3b82f6",
  weekend: "#d1d5db",
  postRelease: "#f97316",
  holiday: "#ef4444",
  black: "#000000",
  white: "#ffffff",
  lightGray: "#f3f4f6",
  mediumGray: "#e5e7eb",
  orange: "#f97316",
  text: "#111111",
  blocked: "#6b7280",
  esteiraPreProd: "#f59e0b",
  chg: "#06b6d4",
  releaseTarget: "#22c55e",
  releaseDay: "#1e40af",
};
export const pdfStyles: PdfStyles = {
  page: {
    width: "794px",
    minHeight: "1123px",
    backgroundColor: COLORS.white,
    color: COLORS.text,
    padding: "32px",
    boxSizing: "border-box",
    fontFamily: "Arial, Helvetica, sans-serif",
    fontSize: "12px",
  },
  blackBar: {
    backgroundColor: "#1f2937",
    color: COLORS.white,
    padding: "12px 16px",
    fontWeight: 700,
    fontSize: "12px",
    letterSpacing: "0.5px",
    textTransform: "uppercase",
    borderRadius: "4px",
    boxShadow: "0 2px 4px rgba(0,0,0,0.1)",
    marginBottom: "8px",
  },
  header: {
    backgroundColor: "#1f2937",
    color: COLORS.white,
    padding: "24px 32px",
    borderRadius: "4px",
    borderLeft: `4px solid ${COLORS.orange}`,
    boxShadow: "0 2px 8px rgba(0,0,0,0.1)",
  },
  title: {
    marginTop: "16px",
    textAlign: "center",
    color: COLORS.orange,
    fontSize: "26px",
    fontWeight: 700,
    letterSpacing: "0.5px",
  },
  table: {
    width: "100%",
    borderCollapse: "collapse",
    fontSize: "12px",
    margin: "12px 0",
    borderRadius: "4px",
    overflow: "hidden",
    boxShadow: "0 1px 3px rgba(0,0,0,0.1)",
  },
  infoCell: {
    border: "none",
    borderBottom: `2px solid ${COLORS.mediumGray}`,
    backgroundColor: "#f9fafb",
    padding: "12px 16px",
    verticalAlign: "middle",
    fontSize: "12px",
    lineHeight: "1.6",
  },
  th: {
    border: "none",
    borderBottom: `3px solid ${COLORS.orange}`,
    backgroundColor: "#f3f4f6",
    padding: "12px 16px",
    textAlign: "left",
    fontWeight: 700,
    fontSize: "11px",
    letterSpacing: "0.5px",
    textTransform: "uppercase",
    color: "#374151",
  },
  thCenter: {
    border: "none",
    borderBottom: `3px solid ${COLORS.orange}`,
    backgroundColor: "#f3f4f6",
    padding: "12px 16px",
    textAlign: "center",
    fontWeight: 700,
    fontSize: "11px",
    letterSpacing: "0.5px",
    textTransform: "uppercase",
    color: "#374151",
  },
  td: {
    border: "none",
    borderBottom: `1px solid ${COLORS.mediumGray}`,
    backgroundColor: "#ffffff",
    padding: "10px 16px",
    fontSize: "12px",
    color: "#111111",
  },
  tdCenter: {
    border: "none",
    borderBottom: `1px solid ${COLORS.mediumGray}`,
    backgroundColor: "#ffffff",
    padding: "10px 16px",
    textAlign: "center",
    fontSize: "12px",
    fontWeight: 500,
    color: "#374151",
  },
  sectionContent: {
    backgroundColor: "#ffffff",
    fontSize: "12px",
    border: `1px solid ${COLORS.mediumGray}`,
    borderRadius: "4px",
    borderTop: "none",
    overflow: "hidden",
  },
  sectionLine: {
    borderBottom: `1px solid ${COLORS.mediumGray}`,
    padding: "10px 16px",
    lineHeight: "1.6",
  },
  timelineTable: {
    margin: "12px 0",
    borderCollapse: "collapse",
    fontSize: "12px",
    boxShadow: "0 2px 8px rgba(0,0,0,0.12)",
    borderRadius: "6px",
    overflow: "hidden",
    width: "100%",
  },
  timelineCell: {
    width: "56px",
    height: "40px",
    border: "none",
    verticalAlign: "middle",
    textAlign: "center",
    boxSizing: "border-box",
    padding: 0,
    lineHeight: "40px",
    fontSize: "11px",
    fontWeight: 700,
    color: "#374151",
    backgroundColor: "#f3f4f6",
    borderBottom: "1px solid #e5e7eb",
  },
  timelineWeekCell: {
    width: "56px",
    height: "36px",
    border: "none",
    verticalAlign: "middle",
    textAlign: "center",
    boxSizing: "border-box",
    padding: 0,
    lineHeight: "36px",
    fontSize: "12px",
    fontWeight: 700,
    color: "#111111",
    backgroundColor: "#ffffff",
    borderBottom: "2px solid #e5e7eb",
  },
  timelineColorCell: {
    width: "56px",
    height: "36px",
    border: "none",
    boxSizing: "border-box",
    padding: 0,
    borderRadius: "3px",
    position: "relative",
  },
  legendWrapper: {
    marginTop: "24px",
    display: "grid",
    gridTemplateColumns: "repeat(2, 1fr)",
    gap: "12px",
    fontSize: "11px",
    backgroundColor: "#f9fafb",
    padding: "16px",
    borderRadius: "4px",
    border: "1px solid #e5e7eb",
  },
  legendItem: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
  },
  legendBox: {
    width: "28px",
    height: "28px",
    border: `1px solid ${COLORS.black}`,
    display: "inline-block",
  },
};