import type { CSSProperties } from "react";
type PdfStyles = Record<string, CSSProperties>;
export const COLORS = {
  desenvolvimento: "#58bf63",
  subida: "#8e44ad",
  testes: "#4a90e2",
  weekend: "#bdbdbd",
  postRelease: "#943333",
  holiday: "#d32f2f",
  black: "#000000",
  white: "#ffffff",
  lightGray: "#e5e5e5",
  mediumGray: "#d4d4d4",
  orange: "#f97316",
  text: "#111111",
  blocked: "#272525",
  esteiraPreProd: "#f59e0b",
  chg: "#00bcd4",
  releaseTarget: "#00bcd4",
  releaseDay: "#2f4292",
};
export const pdfStyles: PdfStyles = {
  page: {
    width: "794px",
    minHeight: "1123px",
    backgroundColor: COLORS.white,
    color: COLORS.text,
    padding: "32px",
    boxSizing: "border-box",
    fontFamily: "Arial, Helvetica, sans-serif",
    fontSize: "12px",
  },
  blackBar: {
    backgroundColor: COLORS.black,
    color: COLORS.white,
    padding: "6px 10px",
    fontWeight: 700,
    fontSize: "13px",
  },
  header: {
    backgroundColor: COLORS.black,
    color: COLORS.white,
    padding: "20px",
  },
  title: {
    marginTop: "16px",
    textAlign: "center",
    color: COLORS.orange,
    fontSize: "24px",
    fontWeight: 700,
  },
  table: {
    width: "100%",
    borderCollapse: "collapse",
    fontSize: "12px",
  },
  infoCell: {
    border: `1px solid ${COLORS.black}`,
    backgroundColor: COLORS.lightGray,
    padding: "8px",
    verticalAlign: "top",
  },
  th: {
    border: `1px solid ${COLORS.white}`,
    backgroundColor: COLORS.mediumGray,
    padding: "8px",
    textAlign: "left",
    fontWeight: 700,
  },
  thCenter: {
    border: `1px solid ${COLORS.white}`,
    backgroundColor: COLORS.mediumGray,
    padding: "8px",
    textAlign: "center",
    fontWeight: 700,
  },
  td: {
    border: `1px solid ${COLORS.white}`,
    backgroundColor: COLORS.lightGray,
    padding: "8px",
  },
  tdCenter: {
    border: `1px solid ${COLORS.white}`,
    backgroundColor: COLORS.lightGray,
    padding: "8px",
    textAlign: "center",
    fontSize: "16px",
  },
  sectionContent: {
    backgroundColor: COLORS.lightGray,
    fontSize: "12px",
  },
  sectionLine: {
    borderBottom: `1px solid ${COLORS.white}`,
    padding: "5px 10px",
  },
  timelineTable: {
    margin: "0 auto 6px auto",
    borderCollapse: "collapse",
    fontSize: "12px",
  },
  timelineCell: {
    width: "32px",
    height: "26px",
    border: "1px solid #333",
    verticalAlign: "middle",
    textAlign: "center",
    boxSizing: "border-box",
    padding: 0,
    lineHeight: "26px",
    fontSize: "11px",
    fontWeight: 500,
    color: "#222",
  },
  timelineWeekCell: {
    width: "32px",
    height: "24px",
    border: "1px solid #333",
    verticalAlign: "middle",
    textAlign: "center",
    boxSizing: "border-box",
    padding: 0,
    lineHeight: "24px",
    fontSize: "10px",
    fontWeight: 500,
    color: "#555",
  },
  timelineColorCell: {
    width: "32px",
    height: "20px",
    border: "1px solid #333",
    boxSizing: "border-box",
    padding: 0,
  },
  legendWrapper: {
    marginTop: "20px",
    display: "flex",
    flexWrap: "wrap",
    justifyContent: "center",
    gap: "20px",
    fontSize: "12px",
  },
  legendItem: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
  },
  legendBox: {
    width: "28px",
    height: "28px",
    border: `1px solid ${COLORS.black}`,
    display: "inline-block",
  },
};