import { type DragEvent, useState } from "react";
import type { Estimativa } from "@/types";
import {
  parseDateBR, isValidDate, sameDateBR, addDays, parseDateRangeList,
  parseDiasParadosList, normalizeDateList, getTimelineColor, getTimelineLabel,
  isEsteiraPreProdDay, isHoliday, isPostRelease, isReleaseDay, isWeekend,
  isParadoDay, getChgDates, getWorkingDays
} from "@/utils";
import { calcularTermino } from "@/components/estimativa-pacotes";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Accordion, AccordionItem, AccordionTrigger, AccordionContent } from "@/components/ui/accordion";
import { COLORS } from "@/styles";
import { cn } from "@/lib/utils";
import {
  Plus,
  Trash,
  CaretRight,
  Check,
  CalendarBlank,
  Note,
  ListChecks,
  Clock,
  X
} from "@phosphor-icons/react";

export interface KanbanColumn {
  id: string;
  title: string;
}

export interface KanbanCustomTask {
  id: string;
  title: string;
  description?: string;
  inicio?: string;
  termino?: string;
  completed?: boolean;
  subtasks?: KanbanCustomTask[];
}

export interface KanbanCard {
  id: string;
  estimateId: string;
  title: string;
  columnId: string;
  notes?: string;
  tasks?: KanbanCustomTask[];
}

interface KanbanPageProps {
  columns: KanbanColumn[];
  cards: KanbanCard[];
  estimativas: Estimativa[];
  onAddColumn: (title: string) => void;
  onUpdateColumnTitle: (id: string, title: string) => void;
  onMoveCard: (cardId: string, columnId: string) => void;
  onUpdateCardNotes: (cardId: string, notes: string) => void;
  onAddCardTask: (cardId: string, task: Omit<KanbanCustomTask, "id" | "completed" | "subtasks">, parentTaskId?: string) => void;
  onUpdateCardTask: (cardId: string, taskId: string, patch: Partial<Omit<KanbanCustomTask, "id" | "subtasks">>) => void;
  onToggleCardTaskCompleted: (cardId: string, taskId: string) => void;
  onRemoveCardTask: (cardId: string, taskId: string) => void;
}

/* ── helpers ─────────────────────────────────────────────────────────────── */

function formatDateBR(dateString: string | undefined): string {
  if (!dateString) return "—";
  if (/^\d{2}\/\d{2}\/\d{4}$/.test(dateString)) return dateString;
  const date = new Date(dateString);
  if (Number.isNaN(date.getTime())) return dateString;
  return date.toLocaleDateString("pt-BR", { day: "2-digit", month: "2-digit", year: "numeric" });
}

function normalizeTaskType(rawTipo: unknown) {
  const tipo = String(rawTipo || "").trim().toLowerCase();
  if (tipo === "front" || tipo === "micro" || tipo === "desenvolvimento") return "desenvolvimento";
  if (tipo === "subida") return "subida";
  if (tipo === "testes" || tipo === "teste") return "testes";
  return "desenvolvimento";
}

function isPlaceholderTask(title: string, atividade: any) {
  const normalizedTitle = String(title || "").trim().toLowerCase();
  const titleSegments = normalizedTitle.split(/:/).map((s) => s.trim()).filter(Boolean);
  const titleWithoutPackage = titleSegments.length > 1 ? titleSegments[titleSegments.length - 1] : normalizedTitle;
  const hasNoName = !atividade.nome && !atividade.titulo && !atividade.demanda;
  const hasNoDates = !atividade.inicio && !atividade.dataInicio && !atividade.termino && !atividade.dataFim;
  const isDefaultHours = Number(atividade.horas ?? 0) === 8;
  const isDefaultOvertime = Number(atividade.horasOvertime ?? 0) === 0;
  const isAutoGeneratedTitle = /^tarefa\s+\d+$/i.test(titleWithoutPackage);
  return hasNoName && isAutoGeneratedTitle && hasNoDates && isDefaultHours && isDefaultOvertime;
}

function getTasksForEstimate(estimate: Estimativa) {
  const tasks: Array<{ id: string; title: string; tipo: string; inicio: string; termino: string; dias?: number }> = [];

  if (Array.isArray(estimate.atividades)) {
    estimate.atividades.forEach((atividade, index) => {
      const title = atividade.nome || atividade.titulo || atividade.demanda || `Tarefa ${index + 1}`;
      if (isPlaceholderTask(title, atividade)) return;
      tasks.push({
        id: atividade.id ?? `atividade-${index}`,
        title,
        tipo: normalizeTaskType(atividade.tipo),
        inicio: atividade.inicio || atividade.dataInicio || "",
        termino: atividade.termino || atividade.dataFim || "",
      });
    });
  }

  if (estimate.tipo === 'estimativa-pacotes' && Array.isArray(estimate.pacotes)) {
    estimate.pacotes.forEach((pacote, pacoteIndex) => {
      if (Array.isArray(pacote.atividades)) {
        pacote.atividades.forEach((atividade, index) => {
          const title = `${pacote.nome ? `${pacote.nome}: ` : ""}${atividade.nome || atividade.titulo || atividade.demanda || `Tarefa ${index + 1}`}`;
          if (isPlaceholderTask(title, atividade)) return;
          const workDays = Math.max(1, Math.ceil(Number(atividade.horas || 0) / 8));
          let termino = atividade.termino || atividade.dataFim || "";
          if (!termino && atividade.inicio) {
            termino = calcularTermino(
              atividade.inicio,
              Number(atividade.horas || 0),
              normalizeDateList(estimate.feriados || ""),
              normalizeDateList(estimate.releases || ""),
              atividade.overtime || { tombamentoDates: [], feriadoDates: [], fimDeSemanaDates: [] },
              Number(atividade.horasOvertime || 0),
              parseDiasParadosList(estimate.diasParados || "")
            );
          }
          tasks.push({
            id: atividade.id ?? `pacote-${pacoteIndex}-atividade-${index}`,
            title,
            tipo: normalizeTaskType(atividade.tipo),
            inicio: atividade.inicio || atividade.dataInicio || "",
            termino,
            dias: Number(atividade.dias ?? workDays),
          });
        });
      }
    });
  }

  return tasks.filter((task) => String(task.title || "").trim() !== "");
}

function getFlattenedEstimateActivities(estimate: Estimativa) {
  const activities: Array<{ id: string; nome: string; tipo: string; etapa: string; dias: number; inicio: string; termino: string }> = [];

  if (Array.isArray(estimate.atividades)) {
    estimate.atividades.forEach((atividade, index) => {
      activities.push({
        id: atividade.id ?? `atividade-${index}`,
        nome: atividade.nome || atividade.titulo || atividade.demanda || `Atividade ${index + 1}`,
        tipo: normalizeTaskType(atividade.tipo),
        etapa: String(atividade.etapa ?? "1"),
        dias: Number(atividade.dias ?? 0),
        inicio: atividade.inicio || atividade.dataInicio || "",
        termino: atividade.termino || atividade.dataFim || "",
      });
    });
  }

  if (estimate.tipo === 'estimativa-pacotes' && Array.isArray(estimate.pacotes)) {
    estimate.pacotes.forEach((pacote) => {
      if (Array.isArray(pacote.atividades)) {
        pacote.atividades.forEach((atividade, index) => {
          const title = `${pacote.nome ? `${pacote.nome}: ` : ""}${atividade.nome || atividade.titulo || atividade.demanda || `Atividade ${index + 1}`}`;
          if (isPlaceholderTask(title, atividade)) return;
          const workDays = Math.max(1, Math.ceil(Number(atividade.horas || 0) / 8));
          activities.push({
            id: atividade.id ?? `pacote-${pacote.id ?? pacote.nome ?? "unknown"}-atividade-${index}`,
            nome: title,
            tipo: normalizeTaskType(atividade.tipo),
            etapa: String(atividade.etapa ?? "1"),
            dias: Number(atividade.dias ?? workDays),
            inicio: atividade.inicio || atividade.dataInicio || "",
            termino: atividade.termino || atividade.dataFim || "",
          });
        });
      }
    });
  }

  return activities;
}

function buildEstimateCalendar(estimate: Estimativa) {
  const activities = getFlattenedEstimateActivities(estimate);
  const holidayDates = normalizeDateList(estimate.feriados || "");
  const releaseDates = normalizeDateList(estimate.releases || "");
  const preprodRanges = parseDateRangeList(estimate.esteiraPreProd || "");
  const paradaRanges = parseDiasParadosList(estimate.diasParados || "");
  const releaseDate = estimate.releaseAlvo ? parseDateBR(estimate.releaseAlvo) : new Date(NaN);
  const chgDates = getChgDates(releaseDate, Number(estimate.chgDias || 0), holidayDates);

  const startDate = estimate.inicio ? parseDateBR(estimate.inicio) : new Date(NaN);
  if (!isValidDate(startDate)) {
    return { rows: [] as Array<Array<null>>, rangeStart: null as Date | null, rangeEnd: null as Date | null };
  }

  const etapasOrdenadas = Array.from(new Set(activities.map((a) => String(a.etapa || "1")))).sort((a, b) => Number(a) - Number(b));
  const stageDurations = etapasOrdenadas.map((etapa) => {
    const activitiesOfStage = activities.filter((a) => String(a.etapa || "1") === etapa);
    return Math.max(...activitiesOfStage.map((a) => Number(a.dias || 0)));
  });

  const totalDias = stageDurations.reduce((acc, dias) => acc + dias, 0);
  const validDays = getWorkingDays(startDate, totalDias, releaseDates, holidayDates, paradaRanges);

  let cursor = 0;
  const atividadesCalculadas: Array<{ id: string; nome: string; tipo: string; etapa: string; dias: number; inicio: Date; termino: Date }> = [];

  etapasOrdenadas.forEach((etapa, index) => {
    const activitiesOfStage = activities.filter((a) => String(a.etapa || "1") === etapa);
    const inicioEtapa = validDays[cursor];
    activitiesOfStage.forEach((atividade) => {
      const dias = Number(atividade.dias || 0);
      const termino = validDays[cursor + dias - 1];
      if (isValidDate(inicioEtapa) && isValidDate(termino)) {
        atividadesCalculadas.push({ ...atividade, inicio: inicioEtapa, termino });
      }
    });
    cursor += stageDurations[index] || 0;
  });

  const calculatedEndDate = validDays[validDays.length - 1];
  const endDate = isValidDate(releaseDate) && releaseDate > calculatedEndDate ? releaseDate : calculatedEndDate;

  type TimelineDay = { date: Date; tipo: string; color: string; isReleaseDay: boolean; isEsteiraPreProd: boolean; isChg: boolean };
  const timeline: Array<TimelineDay> = [];
  let current = new Date(startDate);

  while (current <= endDate) {
    const date = new Date(current);
    let tipo = "";
    let color = COLORS.white;

    if (isValidDate(releaseDate) && sameDateBR(date, releaseDate)) {
      tipo = "Release alvo";
      color = COLORS.releaseTarget;
    } else if (isParadoDay(date, paradaRanges, holidayDates, releaseDates)) {
      tipo = "Projeto parado";
      color = COLORS.blocked;
    } else if (isWeekend(date)) {
      tipo = "Fim de semana";
      color = COLORS.weekend;
    } else if (isHoliday(date, holidayDates)) {
      tipo = "Feriado";
      color = COLORS.holiday;
    } else if (isPostRelease(date, releaseDates)) {
      tipo = "Tombamento";
      color = COLORS.postRelease;
    } else {
      const activity = atividadesCalculadas.find((item) => isValidDate(item.inicio) && isValidDate(item.termino) && date >= item.inicio && date <= item.termino);
      if (activity) {
        tipo = getTimelineLabel(activity.tipo, activity.nome);
        color = getTimelineColor(activity.tipo);
      }
    }

    timeline.push({ date, tipo, color, isReleaseDay: isReleaseDay(date, releaseDates), isEsteiraPreProd: isEsteiraPreProdDay(date, preprodRanges), isChg: chgDates.some((d) => sameDateBR(d, date)) });
    current = addDays(current, 1);
  }

  const rows: Array<Array<TimelineDay | null>> = [];
  const blockSize = 15;
  for (let index = 0; index < timeline.length; index += blockSize) {
    const row = timeline.slice(index, index + blockSize);
    while (row.length < blockSize) row.push(null);
    rows.push(row);
  }

  return { rows, rangeStart: startDate, rangeEnd: endDate };
}

/* ── progress helpers ────────────────────────────────────────────────────── */

function countTasks(tasks: KanbanCustomTask[] | undefined): number {
  if (!tasks) return 0;
  return tasks.reduce((count, task) => count + 1 + countTasks(task.subtasks), 0);
}

function countCompleted(tasks: KanbanCustomTask[] | undefined): number {
  if (!tasks) return 0;
  return tasks.reduce((count, task) => count + (task.completed ? 1 : 0) + countCompleted(task.subtasks), 0);
}

function taskProgressPercent(tasks: KanbanCustomTask[] | undefined): number {
  const total = countTasks(tasks);
  if (!total) return 0;
  return Math.round((countCompleted(tasks) / total) * 100);
}

/* ═══════════════════════════════════════════════════════════════════════════
   KanbanPage
   ═══════════════════════════════════════════════════════════════════════════ */

export function KanbanPage({
  columns, cards, estimativas,
  onAddColumn, onUpdateColumnTitle, onMoveCard,
  onUpdateCardNotes, onAddCardTask, onUpdateCardTask,
  onToggleCardTaskCompleted, onRemoveCardTask,
}: KanbanPageProps) {
  const [newColumnName, setNewColumnName] = useState("");
  const [error, setError] = useState("");
  const [dragOverColumnId, setDragOverColumnId] = useState<string | null>(null);
  const [checkedTasks, setCheckedTasks] = useState<Record<string, Record<string, boolean>>>({});
  const [showCalendar, setShowCalendar] = useState<Record<string, boolean>>({});
  const [largeCalendar, setLargeCalendar] = useState<Record<string, boolean>>({});
  const [newTaskDrafts, setNewTaskDrafts] = useState<Record<string, { title: string; description: string; inicio: string; termino: string }>>({});

  /* UI state for nested tasks (Todoist-style) */
  const [expandedTasks, setExpandedTasks] = useState<Record<string, boolean>>({});
  const [expandedDescs, setExpandedDescs] = useState<Record<string, boolean>>({});
  const [addingSubtaskTo, setAddingSubtaskTo] = useState<string | null>(null);
  const [inlineSubtaskDraft, setInlineSubtaskDraft] = useState<{ title: string; description: string; inicio: string; termino: string }>({ title: "", description: "", inicio: "", termino: "" });
  const [quickAddOpenForCard, setQuickAddOpenForCard] = useState<string | null>(null);

  /* ── drag & drop ───────────────────────────────────────────────────────── */
  function handleDragStart(event: DragEvent<HTMLDivElement>, cardId: string) {
    event.dataTransfer.setData("text/plain", cardId);
    event.dataTransfer.effectAllowed = "move";
  }
  function handleDragOver(event: DragEvent<HTMLDivElement>, columnId: string) {
    event.preventDefault();
    setDragOverColumnId(columnId);
  }
  function handleDrop(event: DragEvent<HTMLDivElement>, columnId: string) {
    event.preventDefault();
    const cardId = event.dataTransfer.getData("text/plain");
    if (cardId) onMoveCard(cardId, columnId);
    setDragOverColumnId(null);
  }
  function handleDragLeave() {
    setDragOverColumnId(null);
  }

  /* ── column helpers ────────────────────────────────────────────────────── */
  function handleAddColumn() {
    const title = newColumnName.trim();
    if (!title) { setError("Informe o nome da coluna."); return; }
    onAddColumn(title);
    setNewColumnName("");
    setError("");
  }
  function getColumnCards(columnId: string) {
    return cards.filter((card) => card.columnId === columnId);
  }

  /* ── task draft helpers ────────────────────────────────────────────────── */
  function updateNewTaskDraft(cardId: string, field: "title" | "description" | "inicio" | "termino", value: string) {
    setNewTaskDrafts((prev) => ({ ...prev, [cardId]: { ...prev[cardId], [field]: value } }));
  }
  function clearNewTaskDraft(cardId: string) {
    setNewTaskDrafts((prev) => ({ ...prev, [cardId]: { title: "", description: "", inicio: "", termino: "" } }));
  }

  /* ── check helpers (estimate tasks are local-only) ─────────────────────── */
  function toggleTaskChecked(cardId: string, taskId: string) {
    setCheckedTasks((prev) => ({
      ...prev,
      [cardId]: { ...prev[cardId], [taskId]: !prev[cardId]?.[taskId] },
    }));
  }

  /* ── expand / collapse ─────────────────────────────────────────────────── */
  function toggleExpand(taskId: string) {
    setExpandedTasks((prev) => ({ ...prev, [taskId]: !prev[taskId] }));
  }

  /* ── subtask inline add ────────────────────────────────────────────────── */
  function submitInlineSubtask(cardId: string, parentTaskId: string) {
    const { title, description, inicio, termino } = inlineSubtaskDraft;
    if (!title.trim()) return;
    onAddCardTask(cardId, { title: title.trim(), description: description.trim(), inicio, termino }, parentTaskId);
    setInlineSubtaskDraft({ title: "", description: "", inicio: "", termino: "" });
    setAddingSubtaskTo(null);
    setExpandedTasks((prev) => ({ ...prev, [parentTaskId]: true }));
  }

  /* ── quick add top-level task ──────────────────────────────────────────── */
  function submitQuickTask(cardId: string) {
    const draft = newTaskDrafts[cardId];
    if (!draft?.title.trim()) return;
    onAddCardTask(cardId, {
      title: draft.title.trim(),
      description: draft.description.trim(),
      inicio: draft.inicio,
      termino: draft.termino,
    });
    clearNewTaskDraft(cardId);
    setQuickAddOpenForCard(null);
  }

  /* ── render nested task (Todoist-style) ────────────────────────────────── */
  function renderTaskItem(cardId: string, task: KanbanCustomTask, level = 0) {
    const isExpanded = expandedTasks[task.id] ?? true;
    const hasSubtasks = (task.subtasks?.length ?? 0) > 0;
    const isAddingHere = addingSubtaskTo === task.id;

    return (
      <div key={task.id} className="select-none">
        {/* Task row */}
        <div
          className={cn(
            "group flex items-start gap-1.5 rounded-md px-1.5 py-1 transition-colors hover:bg-accent/40",
            task.completed && "opacity-70"
          )}
          style={{ paddingLeft: `${level * 12 + 6}px` }}
        >
          {/* Expand toggle */}
          <button
            onClick={() => toggleExpand(task.id)}
            className={cn(
              "mt-0.5 flex h-4 w-4 items-center justify-center rounded text-muted-foreground transition-opacity hover:text-foreground",
              !hasSubtasks && "invisible"
            )}
          >
            <CaretRight weight="bold" className={cn("h-3 w-3 transition-transform duration-150", isExpanded && "rotate-90")} />
          </button>

          {/* Todoist-style checkbox */}
          <button
            onClick={() => onToggleCardTaskCompleted(cardId, task.id)}
            className={cn(
              "mt-0.5 flex h-[18px] w-[18px] shrink-0 items-center justify-center rounded-full border-2 transition-all duration-150",
              task.completed
                ? "border-emerald-500 bg-emerald-500 text-white"
                : "border-muted-foreground/25 hover:border-muted-foreground/50"
            )}
          >
            {task.completed && <Check weight="bold" className="h-2.5 w-2.5" />}
          </button>

          {/* Title */}
          <div className="min-w-0 flex-1">
            <Input
              value={task.title}
              onChange={(e) => onUpdateCardTask(cardId, task.id, { title: e.target.value })}
              placeholder="Título da tarefa"
              className={cn(
                "h-auto border-0 bg-transparent px-0 py-0 text-sm shadow-none focus-visible:ring-0 focus-visible:ring-offset-0",
                task.completed && "text-muted-foreground line-through"
              )}
            />
            {/* Meta row: description + dates (compact) */}
            {(task.description || task.inicio || task.termino) && (
              <div className="mt-0.5 flex flex-wrap items-start gap-2 text-[11px] text-muted-foreground">
                {task.description && (
                  <button
                    onClick={() => setExpandedDescs((prev) => ({ ...prev, [task.id]: !prev[task.id] }))}
                    className="inline-flex items-start gap-1 text-left transition-all"
                    title={expandedDescs[task.id] ? "Recolher descrição" : "Expandir descrição"}
                  >
                    <Note className="mt-0.5 h-3 w-3 shrink-0" />
                    <span className={cn(
                      "leading-relaxed transition-all",
                      expandedDescs[task.id] ? "" : "line-clamp-1 max-w-[180px]"
                    )}>
                      {task.description}
                    </span>
                  </button>
                )}
                {(task.inicio || task.termino) && (
                  <span className="inline-flex items-center gap-1 shrink-0">
                    <CalendarBlank className="h-3 w-3" />
                    {formatDateBR(task.inicio)}
                    {task.inicio && task.termino && " → "}
                    {formatDateBR(task.termino)}
                  </span>
                )}
              </div>
            )}
          </div>

          {/* Hover actions */}
          <div className="flex items-center gap-0.5 opacity-0 transition-opacity group-hover:opacity-100">
            <button
              onClick={() => { setAddingSubtaskTo(task.id); setInlineSubtaskDraft({ title: "", description: "", inicio: "", termino: "" }); }}
              className="flex h-6 w-6 items-center justify-center rounded text-muted-foreground hover:bg-accent hover:text-foreground"
              title="Adicionar subtarefa"
            >
              <Plus className="h-3.5 w-3.5" />
            </button>
            <button
              onClick={() => onRemoveCardTask(cardId, task.id)}
              className="flex h-6 w-6 items-center justify-center rounded text-muted-foreground hover:bg-destructive/10 hover:text-destructive"
              title="Remover"
            >
              <Trash className="h-3.5 w-3.5" />
            </button>
          </div>
        </div>

        {/* Inline add subtask */}
        {isAddingHere && (
          <div
            className="rounded-md px-1.5 py-1.5 hover:bg-accent/30"
            style={{ paddingLeft: `${(level + 1) * 12 + 6}px` }}
          >
            {/* Title row */}
            <div className="flex items-start gap-1.5">
              <div className="mt-0.5 h-[18px] w-[18px] shrink-0 rounded-full border-2 border-dashed border-muted-foreground/30" />
              <input
                autoFocus
                value={inlineSubtaskDraft.title}
                onChange={(e) => setInlineSubtaskDraft((prev) => ({ ...prev, title: e.target.value }))}
                onKeyDown={(e) => {
                  if (e.key === "Enter") submitInlineSubtask(cardId, task.id);
                  if (e.key === "Escape") { setAddingSubtaskTo(null); setInlineSubtaskDraft({ title: "", description: "", inicio: "", termino: "" }); }
                }}
                placeholder="Adicionar subtarefa..."
                className="min-w-0 flex-1 bg-transparent text-sm outline-none placeholder:text-muted-foreground/60"
              />
              <button
                onClick={() => submitInlineSubtask(cardId, task.id)}
                className="flex h-6 w-6 items-center justify-center rounded text-muted-foreground hover:bg-accent hover:text-foreground"
              >
                <Check className="h-3.5 w-3.5" />
              </button>
              <button
                onClick={() => { setAddingSubtaskTo(null); setInlineSubtaskDraft({ title: "", description: "", inicio: "", termino: "" }); }}
                className="flex h-6 w-6 items-center justify-center rounded text-muted-foreground hover:bg-accent hover:text-foreground"
              >
                <X className="h-3.5 w-3.5" />
              </button>
            </div>
            {/* Optional details */}
            <div className="ml-[26px] mt-1.5 space-y-1.5">
              <Textarea
                value={inlineSubtaskDraft.description}
                onChange={(e) => setInlineSubtaskDraft((prev) => ({ ...prev, description: e.target.value }))}
                placeholder="Descrição (opcional)"
                rows={1}
                className="min-h-0 resize-none border-0 bg-transparent px-0 py-0 text-xs shadow-none placeholder:text-muted-foreground/50 focus-visible:ring-0 focus-visible:ring-offset-0"
              />
              <div className="grid grid-cols-2 gap-2">
                <Input
                  type="date"
                  value={inlineSubtaskDraft.inicio}
                  onChange={(e) => setInlineSubtaskDraft((prev) => ({ ...prev, inicio: e.target.value }))}
                  className="h-7 text-[11px]"
                />
                <Input
                  type="date"
                  value={inlineSubtaskDraft.termino}
                  onChange={(e) => setInlineSubtaskDraft((prev) => ({ ...prev, termino: e.target.value }))}
                  className="h-7 text-[11px]"
                />
              </div>
            </div>
          </div>
        )}

        {/* Subtasks */}
        {hasSubtasks && isExpanded && (
          <div className="relative">
            {/* Guide line */}
            <div className="absolute left-[11px] top-0 bottom-0 w-px bg-border/60" style={{ left: `${level * 12 + 11}px` }} />
            <div className="space-y-0.5">
              {task.subtasks!.map((subtask) => renderTaskItem(cardId, subtask, level + 1))}
            </div>
          </div>
        )}
      </div>
    );
  }

  /* ── progress ring (SVG) ───────────────────────────────────────────────── */
  function ProgressRing({ percent, size = 16 }: { percent: number; size?: number }) {
    const stroke = 2.5;
    const radius = (size - stroke) / 2;
    const circumference = radius * 2 * Math.PI;
    const offset = circumference - (percent / 100) * circumference;
    return (
      <div className="relative inline-flex items-center justify-center" style={{ width: size, height: size }}>
        <svg width={size} height={size} className="-rotate-90">
          <circle cx={size / 2} cy={size / 2} r={radius} fill="none" stroke="currentColor" strokeWidth={stroke} className="text-muted/60" />
          <circle cx={size / 2} cy={size / 2} r={radius} fill="none" stroke="currentColor" strokeWidth={stroke}
            className={cn("transition-all duration-500", percent === 100 ? "text-emerald-500" : "text-primary")}
            strokeDasharray={circumference}
            strokeDashoffset={offset}
            strokeLinecap="round"
          />
        </svg>
        {percent === 100 && <Check weight="bold" className="absolute text-emerald-500" style={{ width: size * 0.55, height: size * 0.55 }} />}
      </div>
    );
  }

  /* ════════════════════════════════════════════════════════════════════════ */

  return (
    <div className="flex h-full flex-col gap-5">
      {/* Header */}
      <div className="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between">
        <div>
          <h1 className="text-xl font-semibold tracking-tight">Quadro Kanban</h1>
          <p className="text-sm text-muted-foreground">Organize suas estimativas e acompanhe o progresso.</p>
        </div>
        <div className="flex items-center gap-2">
          <Input
            value={newColumnName}
            onChange={(e) => setNewColumnName(e.target.value)}
            onKeyDown={(e) => e.key === "Enter" && handleAddColumn()}
            placeholder="Nova coluna..."
            className="h-9 w-56 bg-background"
          />
          <Button size="sm" onClick={handleAddColumn} className="gap-1">
            <Plus className="h-4 w-4" /> Criar
          </Button>
        </div>
        {error && <p className="text-xs text-destructive">{error}</p>}
      </div>

      {/* Empty state */}
      {columns.length === 0 && (
        <Card className="border-dashed">
          <CardContent className="flex flex-col items-center justify-center gap-3 py-12 text-center">
            <div className="flex h-12 w-12 items-center justify-center rounded-full bg-muted">
              <ListChecks className="h-6 w-6 text-muted-foreground" />
            </div>
            <div>
              <p className="text-sm font-medium">Seu quadro está vazio</p>
              <p className="text-xs text-muted-foreground">Crie uma coluna para começar. Favoritar uma estimativa adiciona um card automaticamente.</p>
            </div>
          </CardContent>
        </Card>
      )}

      {/* Board */}
      {columns.length > 0 && (
        <div className="flex flex-1 gap-5 overflow-x-auto pb-2">
          {columns.map((column) => {
            const columnCards = getColumnCards(column.id);
            const isDropTarget = dragOverColumnId === column.id;

            return (
              <div
                key={column.id}
                className={cn(
                  "flex w-[340px] shrink-0 flex-col gap-3 transition-colors",
                  isDropTarget && "rounded-2xl ring-2 ring-primary/30 bg-primary/5"
                )}
                onDragOver={(e) => handleDragOver(e, column.id)}
                onDrop={(e) => handleDrop(e, column.id)}
                onDragLeave={handleDragLeave}
              >
                {/* Column header */}
                <div className="flex items-center justify-between px-1">
                  <div className="flex items-center gap-2">
                    <div className="h-2 w-2 rounded-full bg-primary/70" />
                    <Input
                      value={column.title}
                      onChange={(e) => onUpdateColumnTitle(column.id, e.target.value)}
                      className="h-auto w-auto border-0 bg-transparent px-0 py-0 text-sm font-semibold shadow-none focus-visible:ring-0 focus-visible:ring-offset-0"
                    />
                    <span className="flex h-5 min-w-[20px] items-center justify-center rounded-full bg-muted px-1.5 text-[11px] font-medium text-muted-foreground">
                      {columnCards.length}
                    </span>
                  </div>
                </div>

                {/* Column body */}
                <div className={cn(
                  "flex flex-1 flex-col gap-3 rounded-2xl p-3 transition-colors min-h-[140px]",
                  "bg-muted/40 dark:bg-muted/20"
                )}>
                  {columnCards.map((card) => {
                    const estimate = estimativas.find((item) => item.id === card.estimateId && item.tipo === 'estimativa-pacotes');
                    const estimateTasks = estimate ? getTasksForEstimate(estimate).map((task) => ({ ...task, source: 'estimativa' as const })) : [];
                    const productionDate = estimate?.esteiraPreProd || estimate?.releaseAlvo || "";
                    const taskDraft = newTaskDrafts[card.id] || { title: "", description: "", inicio: "", termino: "" };
                    const isQuickAddOpen = quickAddOpenForCard === card.id;
                    const customTaskTotal = countTasks(card.tasks);
                    const customTaskCompleted = countCompleted(card.tasks);
                    const customTaskPercent = taskProgressPercent(card.tasks);

                    return (
                      <Card
                        key={card.id}
                        draggable
                        onDragStart={(e) => handleDragStart(e, card.id)}
                        className={cn(
                          "group cursor-grab rounded-xl border-border/60 bg-card shadow-sm transition-shadow hover:shadow-md active:cursor-grabbing"
                        )}
                      >
                        <CardContent className="space-y-4 p-4">
                          {/* Card header */}
                          <div className="flex items-start justify-between gap-3">
                            <div className="min-w-0 flex-1">
                              <p className="text-sm font-semibold leading-snug text-foreground">{card.title}</p>
                              <p className="mt-0.5 text-[11px] text-muted-foreground">Arraste para mover entre colunas</p>
                            </div>
                            {productionDate && (
                              <span className="shrink-0 inline-flex items-center gap-1 rounded-md bg-secondary px-2 py-1 text-[11px] font-medium text-secondary-foreground">
                                <Clock className="h-3 w-3" />
                                {formatDateBR(productionDate)}
                              </span>
                            )}
                          </div>

                          {/* Notes */}
                          <div className="rounded-lg bg-muted/40 p-2.5">
                            <Textarea
                              value={card.notes ?? ""}
                              onChange={(e) => onUpdateCardNotes(card.id, e.target.value)}
                              placeholder="Anotações..."
                              rows={3}
                              className="min-h-[72px] resize-none border-0 bg-transparent px-0 py-0 text-sm shadow-none placeholder:text-muted-foreground/60 focus-visible:ring-0 focus-visible:ring-offset-0"
                            />
                          </div>

                          {/* Accordions */}
                          <Accordion type="multiple" defaultValue={[]} className="w-full space-y-2">
                            {/* Estimate tasks */}
                            <AccordionItem value={`estimate-tasks-${card.id}`} className="rounded-lg border border-border/60 px-3 py-1 data-[state=open]:bg-muted/30">
                              <AccordionTrigger className="py-2 hover:no-underline">
                                <span className="flex items-center gap-2 text-sm font-medium">
                                  <ListChecks className="h-4 w-4 text-muted-foreground" />
                                  Tarefas da estimativa
                                  <span className="rounded-full bg-muted px-1.5 py-0.5 text-[11px] text-muted-foreground">
                                    {estimateTasks.length}
                                  </span>
                                </span>
                              </AccordionTrigger>
                              <AccordionContent className="pb-2 pt-1">
                                {estimateTasks.length > 0 ? (
                                  <ul className="space-y-1">
                                    {estimateTasks.map((task) => (
                                      <li
                                        key={task.id}
                                        className="flex items-start gap-2 rounded-md px-2 py-1.5 text-sm hover:bg-accent/30"
                                      >
                                        <input
                                          type="checkbox"
                                          checked={Boolean(checkedTasks[card.id]?.[task.id])}
                                          onChange={() => toggleTaskChecked(card.id, task.id)}
                                          className="mt-0.5 h-4 w-4 shrink-0 rounded border-muted-foreground/30 text-primary focus:ring-primary"
                                        />
                                        <div className="min-w-0 flex-1">
                                          <span className="font-medium">{task.title}</span>
                                          <div className="mt-0.5 flex flex-wrap gap-x-3 text-[11px] text-muted-foreground">
                                            <span>Início: {formatDateBR(task.inicio)}</span>
                                            <span>Término: {formatDateBR(task.termino)}</span>
                                          </div>
                                        </div>
                                      </li>
                                    ))}
                                  </ul>
                                ) : (
                                  <p className="text-xs text-muted-foreground">Nenhuma tarefa de estimativa.</p>
                                )}
                              </AccordionContent>
                            </AccordionItem>

                            {/* Custom tasks */}
                            <AccordionItem value={`custom-tasks-${card.id}`} className="rounded-lg border border-border/60 px-3 py-1 data-[state=open]:bg-muted/30">
                              <AccordionTrigger className="py-2 hover:no-underline">
                                <span className="flex flex-1 items-center gap-2 text-sm font-medium">
                                  <ListChecks className="h-4 w-4 text-muted-foreground" />
                                  Tarefas
                                  {customTaskTotal > 0 && (
                                    <span className="ml-auto flex items-center gap-2">
                                      <span className="text-[11px] text-muted-foreground">
                                        {customTaskCompleted}/{customTaskTotal}
                                      </span>
                                      <ProgressRing percent={customTaskPercent} size={16} />
                                    </span>
                                  )}
                                </span>
                              </AccordionTrigger>
                              <AccordionContent className="pb-2 pt-1">
                                {/* Task list */}
                                <div className="space-y-0.5">
                                  {card.tasks && card.tasks.length > 0 ? (
                                    card.tasks.map((task) => renderTaskItem(card.id, task))
                                  ) : (
                                    <p className="px-2 py-3 text-xs text-muted-foreground">Nenhuma tarefa criada.</p>
                                  )}
                                </div>

                                {/* Quick add */}
                                <div className="mt-2">
                                  {!isQuickAddOpen ? (
                                    <button
                                      onClick={() => setQuickAddOpenForCard(card.id)}
                                      className="flex w-full items-center gap-2 rounded-md px-2 py-1.5 text-sm text-muted-foreground transition-colors hover:bg-accent/40 hover:text-foreground"
                                    >
                                      <Plus className="h-4 w-4" /> Adicionar tarefa
                                    </button>
                                  ) : (
                                    <div className="space-y-2 rounded-lg border border-border/60 bg-background p-3">
                                      <Input
                                        autoFocus
                                        value={taskDraft.title}
                                        onChange={(e) => updateNewTaskDraft(card.id, "title", e.target.value)}
                                        onKeyDown={(e) => { if (e.key === "Enter") submitQuickTask(card.id); if (e.key === "Escape") { setQuickAddOpenForCard(null); clearNewTaskDraft(card.id); } }}
                                        placeholder="Nome da tarefa"
                                        className="h-8"
                                      />
                                      <Textarea
                                        value={taskDraft.description}
                                        onChange={(e) => updateNewTaskDraft(card.id, "description", e.target.value)}
                                        placeholder="Descrição (opcional)"
                                        rows={2}
                                        className="resize-none text-sm"
                                      />
                                      <div className="grid grid-cols-2 gap-2">
                                        <Input
                                          type="date"
                                          value={taskDraft.inicio}
                                          onChange={(e) => updateNewTaskDraft(card.id, "inicio", e.target.value)}
                                          className="h-8 text-xs"
                                        />
                                        <Input
                                          type="date"
                                          value={taskDraft.termino}
                                          onChange={(e) => updateNewTaskDraft(card.id, "termino", e.target.value)}
                                          className="h-8 text-xs"
                                        />
                                      </div>
                                      <div className="flex items-center justify-end gap-2">
                                        <Button variant="ghost" size="sm" onClick={() => { setQuickAddOpenForCard(null); clearNewTaskDraft(card.id); }}>
                                          Cancelar
                                        </Button>
                                        <Button size="sm" onClick={() => submitQuickTask(card.id)}>
                                          Adicionar
                                        </Button>
                                      </div>
                                    </div>
                                  )}
                                </div>
                              </AccordionContent>
                            </AccordionItem>
                          </Accordion>

                          {/* Calendar */}
                          <div className="rounded-lg border border-border/60 bg-card">
                            <div className="flex items-center justify-between px-3 py-2">
                              <div className="flex items-center gap-2">
                                <CalendarBlank className="h-4 w-4 text-muted-foreground" />
                                <span className="text-sm font-medium">Calendário</span>
                              </div>
                              <div className="flex items-center gap-1.5">
                                <Button
                                  variant="ghost"
                                  size="sm"
                                  className="h-7 text-xs"
                                  onClick={() => setShowCalendar((prev) => ({ ...prev, [card.id]: !prev[card.id] }))}
                                >
                                  {showCalendar[card.id] ? "Ocultar" : "Visualizar"}
                                </Button>
                                {showCalendar[card.id] && (
                                  <Button
                                    variant="secondary"
                                    size="sm"
                                    className="h-7 text-xs"
                                    onClick={() => setLargeCalendar((prev) => ({ ...prev, [card.id]: !prev[card.id] }))}
                                  >
                                    {largeCalendar[card.id] ? "Reduzir" : "Expandir"}
                                  </Button>
                                )}
                              </div>
                            </div>
                            {showCalendar[card.id] && (
                              <div className={cn(
                                "overflow-x-auto border-t border-border/60 px-3 py-3 text-[11px]",
                                largeCalendar[card.id] ? "max-h-[420px]" : "max-h-[240px]"
                              )}>
                                {(() => {
                                  const calendar = estimate ? buildEstimateCalendar(estimate) : null;
                                  if (!calendar || calendar.rows.length === 0) {
                                    return <p className="text-xs text-muted-foreground">Calendário indisponível.</p>;
                                  }
                                  return (
                                    <div className="space-y-3">
                                      <div className="flex flex-wrap items-center gap-2 text-xs text-muted-foreground">
                                        <span>Período:</span>
                                        <span className="font-medium text-foreground">{formatDateBR(calendar.rangeStart?.toISOString() || "")}</span>
                                        <span>→</span>
                                        <span className="font-medium text-foreground">{formatDateBR(calendar.rangeEnd?.toISOString() || "")}</span>
                                      </div>
                                      {calendar.rows.map((row, rowIndex) => (
                                        <div key={rowIndex} className="space-y-1">
                                          {/* Month header */}
                                          <div className="grid gap-1 text-[10px] uppercase tracking-wider text-muted-foreground" style={{ gridTemplateColumns: "repeat(15, minmax(0, 1fr))" }}>
                                            {row.map((day, index) => {
                                              const prevDay = index > 0 ? row[index - 1] : null;
                                              const showMonth = day && (!prevDay || prevDay.date.getMonth() !== day.date.getMonth());
                                              return <div key={index} className="h-4 text-center">{showMonth ? day.date.toLocaleString("pt-BR", { month: "short" }).toUpperCase() : ""}</div>;
                                            })}
                                          </div>
                                          {/* Weekday header */}
                                          <div className="grid gap-1 text-[10px] font-medium text-muted-foreground" style={{ gridTemplateColumns: "repeat(15, minmax(0, 1fr))" }}>
                                            {row.map((day, index) => (
                                              <div key={index} className="flex h-5 items-center justify-center rounded-sm">
                                                {day ? ["D", "S", "T", "Q", "Q", "S", "S"][day.date.getDay()] : ""}
                                              </div>
                                            ))}
                                          </div>
                                          {/* Date numbers */}
                                          <div className="grid gap-1 text-[11px] font-semibold text-foreground" style={{ gridTemplateColumns: "repeat(15, minmax(0, 1fr))" }}>
                                            {row.map((day, index) => (
                                              <div key={index} className={cn("flex h-7 items-center justify-center rounded-sm", day ? "bg-muted" : "bg-transparent")}>
                                                {day ? String(day.date.getDate()).padStart(2, "0") : ""}
                                              </div>
                                            ))}
                                          </div>
                                          {/* Timeline cells */}
                                          <div className="grid gap-1" style={{ gridTemplateColumns: "repeat(15, minmax(0, 1fr))" }}>
                                            {row.map((day, index) => {
                                              if (!day) return <div key={index} className="h-9 rounded-sm bg-muted/30" />;
                                              const badgeText = day.isReleaseDay ? "🚀" : day.isChg ? "CHG" : day.isEsteiraPreProd ? "PRE" : day.tipo === "feriado" ? "F" : day.tipo === "tombamento" ? "T" : day.tipo === "parado" ? "P" : "";
                                              const cellStyle = {
                                                backgroundColor: day.color || "transparent",
                                                border: day.isEsteiraPreProd ? `2px solid ${COLORS.esteiraPreProd}` : day.isChg ? `2px solid ${COLORS.chg}` : `1px solid hsl(var(--border) / 0.3)`,
                                              };
                                              return (
                                                <div
                                                  key={index}
                                                  className="flex h-9 items-center justify-center rounded-sm text-[10px] font-semibold text-zinc-950 dark:text-zinc-100"
                                                  style={cellStyle}
                                                >
                                                  <span>{badgeText}</span>
                                                </div>
                                              );
                                            })}
                                          </div>
                                        </div>
                                      ))}
                                    </div>
                                  );
                                })()}
                              </div>
                            )}
                          </div>
                        </CardContent>
                      </Card>
                    );
                  })}

                  {columnCards.length === 0 && (
                    <div className="flex flex-col items-center justify-center gap-2 rounded-xl border-2 border-dashed border-border/60 py-8 text-center">
                      <ListChecks className="h-5 w-5 text-muted-foreground/60" />
                      <p className="text-xs text-muted-foreground">Nenhum card nesta coluna.</p>
                    </div>
                  )}
                </div>
              </div>
            );
          })}
        </div>
      )}
    </div>
  );
}
